### ISSUE TITLE
可否增加Table表格选择器

### ISSUE THREAD

**Issue by xzusoft001** [plus-pro-components/plus-pro-components#100]
### 需要增强的组件/模块

PlusSearch

### 描述

可否增加Table表格选择器或者 select Table 选择器，对于大量数据需要作为选择条件时非常有效
https://avuejs.com/form/form-input-table.html

![image](https://github.com/plus-pro-components/plus-pro-components/assets/129942829/f1bac3a8-311c-4df5-aedc-0f5a955bfddd)

**Comment by l-x-f** [comment]
根据团队成员讨论给出答复：
现大版本主要以稳定核心功能为主，暂时不新增新组件，待核心功能稳定后，会考虑增加。
