### ISSUE TITLE
ActionBarButtonsRow.text类型是否可增加方法类型

### ISSUE THREAD

**Issue by RJQingHuan** [plus-pro-components/plus-pro-components#101]
### 需要增强的组件/模块

PlusTable

### 描述

![image](https://github.com/plus-pro-components/plus-pro-components/assets/53939074/fb240d0d-b503-402e-8db2-87d776c5d913)
需要根据row的值显示button的text,目前无法实现,只能添加两个按钮.建议增加可通过方法渲染text的值

```js
 {
    text: row => row.status === '1' ? '锁定' : '解锁',
    props: { type: 'info' },
    confirm: true,
  }
```

**Comment by l-x-f** [comment]
建议很好，下个版本增加。

**Comment by l-x-f** [comment]
[v0.0.8](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
