### ISSUE TITLE
cascader 组件配置 emitPath 和 checkStrictly 时点击异常

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#104]
### plus-pro-components 版本

0.0.7

### vue 版本

最新

### element-plus 版本

最新

### 最小复现环境的链接

无

### 复现步骤

```
  {
    label: 'cascader',
    prop: 'cascader',
    valueType: 'cascader',
    options: cascaderOptions,
    fieldProps: {
      props: {
        emitPath: false,
        checkStrictly: true
      }
  }
}
```
当增加```props: {
        emitPath: false,
        checkStrictly: true
      }```的时候，点击两次才可以选中
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/140ad83c-490c-411a-88ae-8561fb089b47)

### 期望的行为

点击一次就可以选中

### 实际的行为

点击两次才可以

### 构建工具

Vite

**Comment by l-x-f** [comment]
fixed [v0.0.8](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
