### ISSUE TITLE
[el-checkbox] [API] label act as value is about to be deprecated in version 3.0.0, please use value instead.

### ISSUE THREAD

**Issue by RJQingHuan** [plus-pro-components/plus-pro-components#105]
### plus-pro-components 版本

0.0.6

### vue 版本

3.4.21

### element-plus 版本

2.6.2

### 最小复现环境的链接

无

### 复现步骤

![image](https://github.com/plus-pro-components/plus-pro-components/assets/53939074/80788b1a-32fd-40e6-a3ed-2597f9f202da)
控制台警告

### 期望的行为

无警告

### 实际的行为

有警告

### 构建工具

Vite

**Comment by l-x-f** [comment]
fixed [v0.0.8](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
