### ISSUE TITLE
PlusDialogFormInstance.formInstance类型错误

### ISSUE THREAD

**Issue by RJQingHuan** [plus-pro-components/plus-pro-components#109]
### plus-pro-components 版本

0.0.6

### vue 版本

3.4.21

### element-plus 版本

2.6.2

### 最小复现环境的链接

无

### 复现步骤

![image](https://github.com/plus-pro-components/plus-pro-components/assets/53939074/9a504d97-2fa9-4328-87e0-4e7ac8b31f89)

### 期望的行为

希望`formInstance`类型为

```typescript
interface PlusDialogFormInstance {
  formInstance?:  import('element-plus').FormInstance
}
```

### 实际的行为

类型为`any`,并且不是可选. 在弹窗打开之前`formInstance`的类型为`null`

### 构建工具

Vite

**Comment by l-x-f** [comment]
formInstance的类型已超过ts可推断的最大类型。
