### ISSUE TITLE
.plus-table .el-popper的max-width使用css变量,方便修改

### ISSUE THREAD

**Issue by RJQingHuan** [plus-pro-components/plus-pro-components#110]
### 需要增强的组件/模块

table

### 描述

![image](https://github.com/plus-pro-components/plus-pro-components/assets/53939074/62e44f09-3d30-48ba-ad13-65ff4de8aee4)

**Comment by l-x-f** [comment]
在element-plus css变量体系下，暂不新增新的css变量。
