### ISSUE TITLE
PlusLayout内使用PlusSearch出现横向滚动条

### ISSUE THREAD

**Issue by RJQingHuan** [plus-pro-components/plus-pro-components#117]
### plus-pro-components 版本

0.0.8

### vue 版本

3.4.21

### element-plus 版本

2.6.2

### 最小复现环境的链接

无

### 复现步骤

plus-pro-components运行dev 将search页面的el-card去掉

![image](https://github.com/plus-pro-components/plus-pro-components/assets/53939074/6d1a3edf-b41c-42cd-9331-6d0acafb4674)

### 期望的行为

无横向滚动条

### 实际的行为

有横向滚动条

### 构建工具

Vite

**Comment by l-x-f** [comment]
问题原因：el-row 宽度大于el-form
现版本解决方案：el-form 上添加 
```css
overflow: hidden;
```

**Comment by l-x-f** [comment]
fixed [v0.0.10](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
