### ISSUE TITLE
可以将 PlusColumn 里面的 label 设置为可选么？

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#119]
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/37863f0f-0803-4be1-a776-4ce676933a73)

这个label如果不写的，默认选择 prop的值作为lable,如果有label的话，则使用label的值

**Comment by l-x-f** [comment]
经团队讨论做出以下回复 ：
1. `“label 设置为可选“`， 这个建议很好，已被采纳，下个版本就会支持。
2. `“label如果不写的，默认选择 prop的值作为lable,如果有label的话，则使用label的值”`，这个通用性不高，暂不采纳。

**Comment by l-x-f** [comment]
[v0.0.10](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
