### ISSUE TITLE
PlusDialogForm组件的submitLoading参数无效

### ISSUE THREAD

**Issue by a2643979238** [plus-pro-components/plus-pro-components#122]
### plus-pro-components 版本

0.0.9

### vue 版本

3.4.21

### element-plus 版本

2.6.3

### 最小复现环境的链接

无

### 复现步骤

![image](https://github.com/plus-pro-components/plus-pro-components/assets/59910855/e8243f6c-b2cf-4465-96a0-0727fb7ce0b8)
直接写死页面上没有任何效果

### 期望的行为

有 loading 效果

### 实际的行为

无 loading 效果

### 构建工具

Vite

**Comment by l-x-f** [comment]
PlusDialogForm的footer使用的是PlusDialog 的footer, submitLoading 并不支持，[文档](https://plus-pro-components.com/components/dialog-form.html#dialogform-slots)中已说明 hasFooter:false。
可以使用 dialog.confirmLoading 参数.  [PlusDialog](https://plus-pro-components.com/components/dialog.html#dialog-attributes)
```jsx
  // jsx
  <PlusDialogForm dialog={{ confirmLoading: true }} />
```

**Comment by a2643979238** [comment]
> PlusDialogForm的页脚使用的是PlusDialog的页脚，不支持submitLoading，[文档](https://plus-pro-components.com/components/dialog-form.html#dialogform-slots)中已说明 hasFooter:false。 可以使用dialog.confirmLoading参数。 [加对话框](https://plus-pro-components.com/components/dialog.html#dialog-attributes)
> 
> ```js
>   // jsx
>   <PlusDialogForm dialog={{ confirmLoading: true }} />
> ```

[好的谢谢，我是看文档这里是这样用的](https://plus-pro-components.com/components/page.html#%E5%A2%9E%E5%88%A0%E6%94%B9%E6%9F%A5-crud)
<img width="637" alt="image" src="https://github.com/plus-pro-components/plus-pro-components/assets/59910855/76ad6ae6-4d37-459a-b623-ce656ea018fc">

**Comment by l-x-f** [comment]
文档错误，感谢指出。

**Comment by l-x-f** [comment]
[v0.0.10](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
