### ISSUE TITLE
国际化不起效果

### ISSUE THREAD

**Issue by lfk0719** [plus-pro-components/plus-pro-components#125]
### plus-pro-components 版本

0.0.10

### vue 版本

3.2.45

### element-plus 版本

2.4.0

### 最小复现环境的链接

无

### 复现步骤

<template>
  <el-config-provider :locale="locale">
    <router-view></router-view>
  </el-config-provider>
</template>

<script setup >

import zhCn from 'element-plus/es/locale/lang/zh-cn'
import plusZhCn from 'plus-pro-components/locale/zh-cn'

const locale = ref({ ...zhCn,...plusZhCn})

</script>

### 期望的行为

应该怎么写是哪里有冲突吗

### 实际的行为

应该怎么写是哪里有冲突吗

### 构建工具

Vite

**Comment by lfk0719** [comment]
![Uploading 3b0b3ac3879a9a987a249d165fd1014.png…]()

**Comment by l-x-f** [comment]
需要提供完整最小复现代码。

**Comment by lfk0719** [comment]
https://github.com/lfk0719/my-vue-app

**Comment by l-x-f** [comment]
@lfk0719 
升级element-plus 到最新版本即可解决。

**Comment by l-x-f** [comment]
问题原因
 npm 的安装机制和 pnpm 不同，导致安装了2个不同版本。建议使用pnpm 。

**Comment by l-x-f** [comment]
下个版本 解决npm 的安装机制问题。

**Comment by l-x-f** [comment]
[fixed v0.0.11](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)

**Comment by xileliu** [comment]
使用yarn 安装的，最新的版本国际化还是不行为啥呢

**Comment by l-x-f** [comment]
> 使用yarn 安装的，最新的版本国际化还是不行为啥呢

有可以复现的代码链接没，提供一下。
