### ISSUE TITLE
autosize 类型推理错误

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#127]
### plus-pro-components 版本

0.0.11

### vue 版本

最新

### element-plus 版本

2.6.3

### 最小复现环境的链接

无

### 复现步骤

![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/01a45929-5ddc-4b96-afac-8f0bfc6936e9)

### 期望的行为

正常

### 实际的行为

错误

### 构建工具

Vite

**Comment by l-x-f** [comment]
临时解决方案。
```ts
  {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      autosize: { minRows: 2, maxRows: 4 }
  }
```

**Comment by l-x-f** [comment]
fiexd 0.1.0-beta.1
