### ISSUE TITLE
无法修改分页参数 固定为page 和pageSize

### ISSUE THREAD

**Issue by SolexMiller** [plus-pro-components/plus-pro-components#129]
### plus-pro-components 版本

0.0.11

### vue 版本

3.4.21

### element-plus 版本

2.6.1

### 最小复现环境的链接

无

### 复现步骤

如题

### 期望的行为

增加相关扩展能够定义分页参数

### 实际的行为

无

### 构建工具

Vite

**Comment by l-x-f** [comment]
具体指的是哪个组件？

**Comment by l-x-f** [comment]
release [v0.1.0](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
