### ISSUE TITLE
antdPro里valueType有一个'dependency'，咱们如何'dependency'呢？

### ISSUE THREAD

**Issue by qidianwei** [plus-pro-components/plus-pro-components#131]

**Comment by l-x-f** [comment]
[PlusColumn](https://plus-pro-components.com/components/config.html) 配置中的 options 支持数组，computed，函数和 Promise。 [PlusColumn](https://plus-pro-components.com/components/config.html) 配置中的 fieldProps和formItemProps 支持对象 object，computed，函数和 Promise。

[数据联动 官方文档](https://plus-pro-components.com/components/form.html#%E6%95%B0%E6%8D%AE%E5%B1%9E%E6%80%A7%E8%81%94%E5%8A%A8)
