### ISSUE TITLE
PlusDatePicker type 不生效

### ISSUE THREAD

**Issue by kobetwenty-four** [plus-pro-components/plus-pro-components#135]
### plus-pro-components 版本

0.0.11

### vue 版本

3.4.21

### element-plus 版本

2.6.3

### 最小复现环境的链接

无

### 复现步骤

```js
{
      label: "上映日期",
      width: 170,
      prop: "updateTime",
      valueType: "plus-date-picker",
      fieldProps: {
        type: "year",
        format: "YYYY-MM-DD",
        rangeSeparator: "-",
        // startProps: {
        //   type: "month"
        // }
      }
    },
```
type设置不生效

### 期望的行为

生效

### 实际的行为

不生效

### 构建工具

Vite

**Comment by l-x-f** [comment]
release [v0.1.0](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
