### ISSUE TITLE
plus-input-tag删除tag后进行表单提交时删除的tag还存在

### ISSUE THREAD

**Issue by kkkkninezzz** [plus-pro-components/plus-pro-components#141]
### plus-pro-components 版本

0.1.0

### vue 版本

3.4.21

### element-plus 版本

2.6.2

### 最小复现环境的链接

https://playground.plus-pro-components.com/#eNqtVs1u20YQfpUFW0AyIJGJnZMqG04MB0iRtIYd9GIZCE2upLWXu8RyKVswdCvQPkJ76K1AT32CHvIyTZHH6De7/JNNOyhQG5CondmZb775dod3wcs8D1clDybBtEiMyC0ruC1zJmO12J8FtpgFBzMlslwby+6Y4fMRO6UPrV7xuTb8nS6VZRs2NzpjswCxZsE37Y6ZYsyuc85OZFkcaVlmatSsvRZcpj/EsuSFWySf19pkM9XEy7E0zo0eJxoRFVeECPHpP9GqsAwgsjMbW872Cd60E/Rg6PLPhbTcnJaSFxN2fjFiUcQ+f/zpn79+//zHj59+/hXpdlzIeakSK7RiQglLQIY7voImR7iiwGEnIrKeD2y8eD4YMfrerb73BheIufFIt8gaIur+gQ/cJiJnj6Ity/MF0C155xeUkLa6/QyNuuRyAqa2Kgocn4zdiNQuJ+z57rNqAVTm5N2poHF2tb1HY8jBES9UXtoxqml8Ei1PEAKYqvyMFXmsJmz3hf+Nit0HVd9Ws4xVKvlZeZkJiwLiYq0SNnQJEarTspYa2qglD6VeDGdBN8Boq6OA9lR/HLEVlmnkNQ5FTy3PcokdeGZs2iqv4XSc60KQGugY6HwWVCSNM51yicUmaW2agBzqV2WrutdYjb4hJedkv2OL0gIieHsGtiqXudZYeynFgpIasVja2nRYuNKx3GXCW10JKKIuiX3lA7k8W8wjU+UM91SsWGHXksMvi81CoIvPWFxa3fGCH6i4BFgNAus1f36xLzcCW9c1Sv93mEiRXPdCrf8O/v7426c/f5lGPcFbhBEg1sVF2w2L6o5RL7u2YBT4u2ecxXl4VWiFu80JalYZ0JFGvbOAS57hVhmT3skA1NZC31FUqvx6EeLeAcjW53A33AtfAFlhI6FSfhvOSynD7Ko9R4/cWv2xe1yruNshD7sgIkGnY+wu2/6wj7h3cVP46rBuwJot4DQXi3ucESwhufk+p7OwzV0spb751q1ZU/IGa7LkyXXP+lVx6/GeGF5wswL6xmahQA6VkPn47Dt+i+fGiCOHs/yk8ZTjtigJo3d7VZL2TMfPoX3jJCDU4n1xfGu5KuqiCKhjw/m7QXb0ROkt3L1wr8PiiYzXC4NrPn0XC9U3Wttxitnrx9wgjKo5POjMWudNMseFS1C8OOpRiz090kHzEKJ/53Bn6wZ8cAcSnKjnOPWnQVkNUjBxVBoDyxtc9rFKeINyq6aHxXinngztpmMvZNpbuXelDb96xqy4oW5ivAzcGe2YEsNRzluhrmEdQnxarvgIrwtXPME4WeK9YXvwWCa9c6qTkpKFPkQFZjgg8wCEYljgKTRcUl53nRZLzi2SVyYKDht9NWtxmh6vEOctTiNX3CCejlO8OVTQ2sAPPbkx2jhXAu88G5CXOl2HcZ5zlQ5pO6zuDURyi1cNtEZKngLMPJYF1B7fxBgKlPqMgJNA2qXjk2Zxpvit60XzgvSYwqq3mjkbNul2gNSWxl3wnlpnIpHs9yiH8tF7kf9FxRxpZXHi6TEsCz58kPaLOzoSan0rKvy5dyzdL7JDjK/LF8IUv2EAkAmEvi+mVkaotlHdQ8kN/sskSIrCa21TN7QPatOw/x3shy+MxK/vqrO36c4XoP7QRR1s/gWFhFTp

### 复现步骤

1. 打开控制台
2. 在不触发输入框焦点的情况下，删除tag
3. 点击保存

### 期望的行为

控制台输出的tag应该只有没有被删除的tag

### 实际的行为

控制台输出的tag包含了被删除的tag

### 系统信息

```shell
浏览器: 124.0.6367.119（正式版本） （64 位）
```

### 构建工具

Vite

**Comment by l-x-f** [comment]
fixed [v0.1.1](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
