### ISSUE TITLE
为什么使用插槽plus-field-* 不会触发 事件formChange

### ISSUE THREAD

**Issue by ckbabby** [plus-pro-components/plus-pro-components#150]
在https://plus-pro-components.com/components/table.html#%E5%8F%AF%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC-%E6%95%B4%E4%BD%93 案例中，为什么name 使用了插槽不会调用formChange,是不是应该添加个onChange 方法将值给plusTable组件然后回调formChange？

**Comment by l-x-f** [comment]
使用了插槽，就意味着脱离了组件的控制，onChange等行为自己完全可控，组件一般不干预插槽的行为。
