### ISSUE TITLE
表单验证规则，组件是选择器控件，里面加了  trigger: "blur"，就会一直爆红

### ISSUE THREAD

**Issue by sosovia** [plus-pro-components/plus-pro-components#151]
### plus-pro-components 版本

0.1.3

### vue 版本

3.4.21

### element-plus 版本

2.7.2

### 最小复现环境的链接

https://playground.plus-pro-components.com/#eNqtWOtuE0cUfpWVVclBim1Iqv6wkog2DRIVLRGg9gdGYrM7tifZnd3uzuZSy1LSitIUSJAQOEAgSsmFpiUXiiCkKLxMdu28Rc/sfe2xkzTkT9ZzznznOmfmnErqS13PjlsolU/1UaTqikjRQIEIQh9SMiMWpRoRzksKlsb6C6mySGQFXdYRKaQGnNkH9odp+8P7+katsfzSvvewLxfu8SCGFcv8GouKVrqgGaownlE1GSn5cWziEQUBoP9VSAU0tiYqFjJhKV+ETbBQESRNsVRidguGpSBTqAIxBxL6cjGN4acpGVingiKSEmyjDMNE1NKBilVdM6hQEQxUFKpC0dBUIQ1mp0MSndIR0JnKg664buECRor8vatOuEcHekY3tIykwT6CCDUBo0AkjZjU169fqDDziaiivHCdfQreCvsz0I8WNpCcF6hhoe5gWUWmKZaAP93YetfYf2DfWrXv36uvbwM6o1fZvxsuu0lFapmnQa7//taZnkmHLNTApRIy8kIhNaJYRiEVl1kg8D8w0I9EPuan6zfAYFcXXxNFHIEgC2lff1/KBJZpOS+c6znrL4ATdeBiXgp43NBfg0DAuqTpU8E61TSFYsbtYTqL0/bKE2dhv76y98XB7ob9qlb/e831VNXd0qRJ0t52mnh+5eliIgVJNKBoOsXgjDAAsRBEIp3Fjcb6C/vXfyIv+5hAPBtfBJdq4Po0RM6PdWBFG2j73ev20Od40BBUlunHwPaAD3Zf8bB7eNhTSFG0iWNqvrLTeLPKg+490iPeB2Rjmxg7C1v2/TUvJ5ojfbY50hOYSmVupD1KIIUnp/b2sPYm2OsDUsxPYhlqU0aH4omM9tnpPNw+vD3fhEgsdQQ2cTAx0S2aSdKLrFINw07IygpAIAkKq0byQk83lAsEgD2eB7kK2Etz9u7PTQpImIbnL3EuRVMS5Uh0x9PATfhA7OHjh43Vj4nAl7EiGwj0DsGaABOgmQRsIo1XP9qbs83UNvAcEU1iWgUl4vdom3nw7l6YrMFfdBiOKSdxelv89dcCE/Up5CROcrOc+sxzZ3mVKye54B5GDi1c5xYDbqUKU3Fn51Q5ca59TtgrG/bc0qfJCRDTOSfs7Xl7r3bqWDE5HXPCnl852Fthp/fUcjrmxMHubWdp3nnON+mkaXFULbcX3TRPFiR46ElhkY1eBPCoqb/ery9v2r9tH9Ze1mfv2vPvuHUxEO8ClTUFiljb/bEHEFfDxtqMs9NcMmWkwgOZWzTLSBob0SZP9ISwnz61b72q763znxDHu883l+ubNWdx72DvLiA1tmYO3q/x3w3HwnMebx5OP2lsPWuP1HOCO/uPNeeX8Bnje7GEi+FTK+5DQ5SxdiIHNrZqp3Hdx0Xn0ftT+Kq+P3f4IlFw/oeLICudxSXuowMR+dox3h2djgJrenx29oQxoHMK8dxGw6DDzaflcHrWufMna/3W7yT1EgRQqQ1//d8HzrPAjiNP19YbZ2Gu5XSZEs9WiiZBTyR2NFQVJxVESt5rMDKwrE38oBnyJaxi2tQ2iRbVTPwTSKgIKiZXtAnAg+cUIHnfnwfB8+woEAhi0Cb5fS00RtBvdhVFxURnQprXULqkvliLOdBVqQJTwBb12sDadUboH/Cs8aGzLgyQmNJui9aX8/pf6HZT3Smvq82oop4dNTUC7b27u+AToDcOvVNIQXujQiebYc0tI0CnTyn4L5eziD5WykKvC619xHO+J9ub/TwnY5PmMJHRZLZoKUpWHYXdvgMLKU6n3A6bw+rjJiHPx5XIYeaoDDTx7WDbsMf1ZvB++KrgNWoCUxGXmnzG1MIKMi57VSfhO5G1P9+4a7H8gT2s5HPWR81JT99hA5nIGAftQxrkcQlRjzx09TtI7BgR5iMwXehIvIJMaMmZjh7bVxbLIejnQz5X24tuCmBSumYOTVJEWKsQKhodShjFWGiwg+mRur3Z3pgXoQRMlQwNhH8rYhJMl/zpTNNEBsZP/mQlm/NHUdFMpuJxs1kDHGimipcc4TQmy0sdCB5A8Hd2wQmLHRT4kRx6MXVaRktgEl8MmBVqCp4YtAx4SdKLcHxFIiH+nKnVmE6DJX/TkJfIbK/PHk/t2ABqHBksmlAX0u4ZjZEkqJEUXcJkjBUUSD5NGUcwUkOjMNvoFspQjqIq421RPGZZkywmLOtB+Mp0pRk5DQ6Fwg1fWQMpTK5Jp2AIVkaIunXeJTFwoLF/4Zooy0PjgHMJTiMiyAA8TYTXE2jkqhYBt3Iiw9DgZvOVdzlDJUc0eSor6lA45S62HajuAEtBVMAsNIqCZFDGrcoFIk6IGCwF0VeZ4ixBoqWh4XCxQNCkG4uiRSR2FtrkJpRq14O4KHSF4s6AptQy3HmC51qXxJKkn5M5TB4g+L+YMYMaYfcc+8xaJupqEXvkjlgKRby+K8I7pNXImGM8uzxDBIImBFBAxQDdnExRGoG1Yda1plz6JDeBZJperrFLsq2qYcA+ubI3j7gSP6v4Z68av19A65txrVPV/wCFTa3K

### 复现步骤

直接执行，打开对话框。先提交按钮，提示需要验证。选择器选择，移开鼠标，操作其他控件。一直爆红。

### 期望的行为

正常显示

### 实际的行为

验证爆红无法消除

### 构建工具

Vite

**Comment by l-x-f** [comment]
trigger: 'change'
