### ISSUE TITLE
添加编辑行，新行无法编辑

### ISSUE THREAD

**Issue by NONO9527** [plus-pro-components/plus-pro-components#155]
### plus-pro-components 版本

v0.1.4

### vue 版本

3.4.21

### element-plus 版本

2.6.2

### 最小复现环境的链接

无

### 复现步骤

push 记录就会出现

### 期望的行为

修复问题

### 实际的行为

无法使用

### 构建工具

Vite

**Comment by LB-king** [comment]
`tableData.value.push({
    name: ''
  });
`
新增一行数据，name是输入框，数值未绑定上

**Comment by l-x-f** [comment]
[fixed v0.1.5](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
