### ISSUE TITLE
对PlusTable的优化建议

### ISSUE THREAD

**Issue by SolexMiller** [plus-pro-components/plus-pro-components#156]
### 需要增强的组件/模块

PlusTable

### 描述

增加PlusTable虚拟表格支持

**Comment by l-x-f** [comment]
等element-plus 虚拟化表格 稳定

**Comment by SolexMiller** [comment]
是否能给PlusTable 提供execl导出的功能呢，或者可以通过hooks的形式提供导出

**Comment by l-x-f** [comment]
@SolexMiller 需要讨论确定

**Comment by sanonz** [comment]
PlusTable 的[displayValue](https://github.com/plus-pro-components/plus-pro-components/blob/dev/packages/components/display-item/src/index.vue#L248) 能否加个 formatValue prop 函数？现在遇到的情况要使用内置 valueType 组件，但是展示的值想要格式化下，比如使用 copy 组件复制的是完整的 hash，但是 hash 太长只展示截取部分：

```js
const columns = [
  {
    label: 'hash',
    prop: 'hash',
    valueType: 'copy',
    formatValue: value => value.substr(6) + '...' + value.substr(-6)
  }
];
```

在比如展示状态，`status` 是数字格式，1 代表正常，2 代表禁用，这样渲染出来是数字：1、2，实际想要：正常、禁用

```js
const columns = [
  {
    label: '状态',
    prop: 'status',
    valueType: 'tag'
  }
];
```

**Comment by l-x-f** [comment]
@sanonz 用render，或者 使用 [表格显示单项插槽](https://plus-pro-components.com/components/table.html#%E8%A1%A8%E6%A0%BC%E6%98%BE%E7%A4%BA%E5%8D%95%E9%A1%B9%E6%8F%92%E6%A7%BD%E9%85%8D%E7%BD%AE)
[render参考文档](https://plus-pro-components.com/components/config.html)
[自定义表格显示文档](https://plus-pro-components.com/components/table.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E6%A0%BC%E9%A1%B9%E5%92%8C%E8%A1%A8%E5%8D%95%E9%A1%B9-render)

render 示例
```ts
const columns = [
  {
    label: 'hash',
    prop: 'hash',
    valueType: 'copy',
    render: value => value.substr(6) + '...' + value.substr(-6)
  }
];
```

**Comment by sanonz** [comment]
使用 render 时，valueType: copy 就失效了，要自己在写个  copy 逻辑，提这个就像简单点实现类似这种功能在 2024年6月20日，11:25，xiaofei ***@***.***> 写道：﻿
@sanonz 用render，或者 使用 表格显示单项插槽
render参考文档
自定义表格显示文档
render 示例
const columns = [
  {
    label: 'hash',
    prop: 'hash',
    valueType: 'copy',
    render: value => value.substr(6) + '...' + value.substr(-6)
  }
];

**Comment by l-x-f** [comment]
可以重新开个issues，将列为新版本功能。此issues将关闭。
