### ISSUE TITLE
PlusColumn 中 prop 属性嵌套问题

### ISSUE THREAD

**Issue by xin-kid** [plus-pro-components/plus-pro-components#159]
### plus-pro-components 版本

0.1.4

### vue 版本

3.4.25

### element-plus 版本

2.7.3

### 最小复现环境的链接

null

### 复现步骤

无

### 期望的行为

```js
export const UserFormColumns: PlusColumn[] = [
  {
    label: "性别",
    prop: "more.gender",
    valueType: "select",
    options: computed(() => {
      if (!store.dict["gender"]) store.fetchDict("gender");
      return store.dict["gender"];
    })
  },
]
```
上面代码中`prop: "more.gender",`，v-model预期结果应该是
```json
more: {
  gender: 0
}
```

### 实际的行为

![1716459037358](https://github.com/plus-pro-components/plus-pro-components/assets/27476277/a26f1915-91d2-4213-8cb2-6ab8135c38eb)
实际是字符串拼接了
```json
more.gender: 0
}
```

### 构建工具

Vite

### 额外留言（可选）

不知道是bug还是我使用问题。。

**Comment by l-x-f** [comment]
就是字符串，不是bug。

**Comment by xin-kid** [comment]
https://plus-pro-components.com/components/config.html 文档里面说prop支持`x.y.z`多级数据格式咋弄，还是暂不支持？

**Comment by l-x-f** [comment]
支持的[参考文档-表格数据多级显示](https://plus-pro-components.com/components/table.html#%E6%95%B0%E6%8D%AE%E5%A4%9A%E7%BA%A7%E6%98%BE%E7%A4%BA)

**Comment by xin-kid** [comment]
是我表达不太清楚，我是用在表单上的，不是表格。表单是不支持对吧？

**Comment by l-x-f** [comment]
嗯嗯
