### ISSUE TITLE
分页查询数据有问题，选择大于1的分页然后点击搜索没有数据或者就几条数据的时候，会查询两遍

### ISSUE THREAD

**Issue by catAlikay** [plus-pro-components/plus-pro-components#161]
### plus-pro-components 版本

^0.1.6

### vue 版本

^3.4.27

### element-plus 版本

^2.7.3

### 最小复现环境的链接

https://plus-pro-components.com/components/page.html#%E5%A2%9E%E5%88%A0%E6%94%B9%E6%9F%A5-crud

### 复现步骤

您直接去组件官网就可以看到具体问题以下贴图
![image](https://github.com/plus-pro-components/plus-pro-components/assets/29424278/f3625ace-15cb-4b1f-9305-3532dbf3d1d3)

### 期望的行为

期望点击搜索查询第一页等

### 实际的行为

比如你选择第六页，然后查询其他条件并且是无数据的时候，会出现先查询第六页，然后在查询第一页的情况。

### 系统信息

```shell
chrome
window11
node20
```

### 构建工具

Vite

### 额外留言（可选）

vite5.2.11

**Comment by l-x-f** [comment]
[fixed v0.1.8](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
