### ISSUE TITLE
PlusPage 和 PlusTable自适应

### ISSUE THREAD

**Issue by FuAdmin** [plus-pro-components/plus-pro-components#164]
### 需要增强的组件/模块

PlusPage PlusTable

### 描述

目前的版本，没有自适应的功能，每页数据多了之后，要一直往下滚动才能看到分页

**Comment by l-x-f** [comment]
添加height就行  [示例](https://playground.plus-pro-components.com/#eNqtV19vG0UQ/yorC3S2sM9pQiVkxaUl5KGoQNREvMQV3dyt7UvWe6fdPSfGsgQvICEh8dYXHpAAVUKqxJ+q8MSnoX/4Fszs7t3t2ZeESkSKfDf/Z3bmt3PL1p0sC+c5aw1au5rNMk41uzWSI0HIbpzM3SO8HPBcHdETzgoKIYMo5flMqOGopZGzl4pxMhm1PAlD78VU00LofXj2RaZU9RIRs4ueteYpZ3SSCKqTVIDysmIQolNNedenzNKY8U8oz9mAgB67K8ZpTQCJh8ln7F6i9IAc39jqkm34v7n1oCZGeTIRAxLIZDLVQcVZ1WJmyIWg3tmaT33G7SrkvSkVEwYy8BtzdrDGqLT6Rbn7Rb13+7WTMCQVySTThIMuVlKNWkQxnWdGIpllqdRkSXLFzBmRFRnLdEaCDE6tl8kUigsyggmtTFJOQy8yBmoQnC0YwVPeM+dwrQljRmgmxzRixLi9n54Td05JPCAin50wad8FncHJKC0TMbEUpanOVZ2m6WSNkKAa9Ixpu1XhN0qF0uSIKX3I5JyRYeF2wrQ9YKoWIiLtDhneKniEWDXsRtC4IyVdhJhje0k4ExM9HUA7bJFVJ5zRrN1O4BS6xPRm3QwhEkovhU+xGRvhWj/ZvA2dvEUCfA1qAkUZDk3WbSv5Jtnp1KRMYSxvOBySG+RdEqg8iphSAfE528g5pxKOZlLn7CAngVNGchBjE8p6KLbYgp2bgrc7fve7x1VJ3CwB1nVgq0tV2RDH/nyZubUyoS15adg+mJ+1Y15C9g44um7yyxGHLh2WXb9b+bxlo8f/QjScIzqEBQ6A3s26Hw/DBt4gHD8A0WMbXpktpycMEgmef/vNy8e/VGWEOcmAbI7ZZeR4G6ovv3724vMvNlRtP1RkE/URzCnyGGeRrnhphoACzePCw79aTxa+Xnz386vHPzz/8vf6gRvbwN6qkwGIU4kYyGIfAT2ZRifP//jtKic3mp2cAPd1vFgXf//5pNnLdrOXBeM8PX+tbH789dXTn5qd7PynehWPD65phBfff/XyyV8bjQAj39wFNcY4YTw+AA3ograLzwLoZZhlQH9gLXqDfV2Qj5798+jpZpAAGc1RwoyzXpZEZ4Ay3mybYlQz5/AaJqwBsLVcrGP30mCHgwELJEf4aHCAntPEuxVCZ7wCshJHLBaAChoouWioxjGmXfAkojqakjaTMpUdsqyQykbWfM2DofanBQIBqrinDtQ/TWIv1zpKgVqpVRSsvNxsPiVI1qi7fbsomLWg1W3Ze74H91l4qlIBW94SLY0cA9aIAURg0h+1AF1mcL338MZHBuwuWkNj9fu5yM4mISwAfV/m9na4E74Na4vSfXPPhOOc83B2CtrdwmjD+nCZ7QZRZ7du8rYfRD/B+vdghb3M7CXiftxo3raoWEHVtAIhuAbWaoZhJZzJjy3s1mpHEV8+MDQtc1bGGk1ZdNZAP1UXNt4DyRR2q5efphIO1bL3Dz9iF/BcMmHRzWEJv4p5nym4uTBGK/Zejq0pPTkT7V3TAoAUR2r/QjOhiqQwUAcGJm8o1t4VqVfh7oQ7XhUPOF1MZArOP6SJKD4y3CLrltdiEYWvELduhn33RRJ4e62RxisZkA5Dsc1RrqhhU+vA4YGJZk0YFm9UBLxUGzeu4hgO7OW1TRzHqdkNpFVGCpXYy6UEzl1ABSpgNS6irOW0mcwV23ahtG8bGXWduN/aIFeA0ZxJPE2AkcDMqMeKJIN07iXiDLEJmi/lc9aF2+EUVosumUo2dhgMhbAq3ArHaZSjs9CacMG0A2QHUFC4LOAplIyjX6UXnKkpY/AVVbDQOPDwp6TRON6fgx3EMCaYBHspjQOMyIRWGd6UNFhsRDF4I1kGeZLGi5BmGRNxG9WBC305EpxpWIrhaDhnAMBkTLmCbrd3B7o+xMCxQSrS/kFJHAl2Yc5inIsIZ+GS3oSLzFQwGRPY6Z27jruEq9IaFjbJsKFz0B9YcG+YDGynGiYeH0PYetsbbq/V8FqoknWlsHNvqrSepFcYm5fbJvBjAQKYJWB6vZmqNoJsy67bbLngdW6CCD54TODwJXJ5qOWB/e/BPrzmSnxj6WZv5d8vEPVDP+rW6l8iJOa5)

**Comment by dlpuzcl** [comment]
单独的Table组件可以加height，但是Page组件，点expand的时候Table就溢出去了
![image](https://github.com/plus-pro-components/plus-pro-components/assets/42840739/bbfcd71f-44ff-4a90-a4b8-ff27ce5596e0)

**Comment by newarea0** [comment]
我也有类似需求，通过 flex 布局来解决的：

```vue
<script lang="ts" setup>
// ...
</script>

<template>
  <div class="auto-layout">
    <PlusPage />
 </div>
</template>

<style lang="scss">
// 高度自适应
.auto-layout {
  padding: 16px;
  height: calc(100vh - var(--pro-layout-height-header));

  .plus-page {
    display: flex;
    flex-direction: column;
    height: 100%;

    .el-card.plus-page__table_wrapper {
      flex: 1;

      .el-card__body {
        height: 100%;

        .plus-table {
          display: flex;
          flex-direction: column;
          height: 100%;

          .el-table {
            flex: 1;
          }

          .plus-pagination {
            padding-bottom: 0;
          }
        }
      }
    }
  }
}
</style>
```
![2024-08-22-13-52-31](https://github.com/user-attachments/assets/701d0494-6f54-4da5-822c-d9796f8e7d71)
