### ISSUE TITLE
表单属性的增加

### ISSUE THREAD

**Issue by sun511821811** [plus-pro-components/plus-pro-components#165]
### plus-pro-components 版本

0.18

### vue 版本

3.4.27

### element-plus 版本

2.7.3

### 最小复现环境的链接

https://playground.plus-pro-components.com/#eNqtVd2K20YUfpVBLcgLaznpll6Y3SXtsoGUtDVNaC+iQBTp2NbuaCRmRl5vjS/TQG8LvepNLgKh9Bn6NrvkMfqdGVmWvXbTQK6kmfP3ne/8zCL4uqqiWU3BMDi2VFQysXQaKyGOSfbTRGfugONI1uZhqQsx6xdlRvIkDoyFchwImbyE8lWe2Slu79+7V81xOxzrssB5YfJfaBiaIpEyXLIgLWVdKANZ8xcHTRTEWYEQn9mylDav+nlaqlbugfGVGLJjDvgVnBp7LflQJHqSq76ksR2K+w7J6fHPiVa5mojB6fGgsV4HHGykzRerVD0PbNEQsaGLo0l1XlnkryYIbZGHMGTrCtK8qEptxUJoGoulYC5ECJ7DVmSvK4Kcg505Gg7Fw5xk9lMiazKtTQV5v9JlPy1hp0hZs/axEKvUVuoPSFIBpT7bDThT0/dhY8UHC6aY3RMGdtwJeNpbcLq5qmowF97+8fr2z79htjxYmzblGnZAP3sOV8/Y0pkL3wxw8P6f329evb1982t46AXIocK9C7C6m3HopyBiW9DUnv28/uvmt3fv37y9efVu7ZO1lrF6zjXxVQDnwWHgeekXSRVdmFKhqx2suBGgQsMV0DjoUsWCOJhaW5nhYFCr6nISgXEUf63z4IvoKPpykOXGDnKV0Twa11JGxQWsG9xxsKNe+3zvUG38brrcU9N9bveod3Gz+4bCJVizBkrjfLLFGcPKJekfKpvDyQZ3GOby6lt3Z3VNLdZ0SunljvsLg0lkvCNNhvQM6FuZxcyS9eLzJ9/THP+tEMumlk2ue4Q/kkEvMkav9k2tMsDu6Dm0j1wLYFiemvO5JWVWSTFQx4bTjwOQdfYfqa/hHkVHHRZHMrme6BLBv0tytVqqzY7Y2gvYus3ARoNmA3en2mnzkI10yVB8c7RDHu1qHRQPLnZb9jDEnUHBYXPXM5zB9oJDSrvDIK0WKZg4q7WG5BE2RKJS2r3t7ibzP9bbuW9ktm3Uu63d2Wkz0lxNrKLQzWhHlGpCOo9zdQlpD81XyhkdYvtdUGoPxRRr8ECcnPryehPplbMyrTlY5F00YHohi0MQil2Hv0iT5LjuATJTIuuWkxOxc8j4094lWXY+g5/HmEZSpOGvTLKQETloa8d3NUnrUjtVBu80W5Avy+w6SqqKVNZjc0jRl7GSZLHUURopKQOYcSINuj25SnJkitBPGDg3yPrqfNRexormrhbjWqU8C3t6s3fgGczHoteGOwBSW2s4WVHrRNwkJzs6h+PxC+RPnMxZqSwmnn+j2lDvTtgPWnRaaK3bUOHn3rG0nWSHGJ+XT0QouhIAUORwvd1M6zZCtm3X3W258GNegtQY32v8Du+F2hbsk4N98YEn8fNFM3vL7vsC1C+6qIPlv2hKrdw=

### 复现步骤

它一直存在问题

### 期望的行为

element-plus表单的所有属性均有定义

### 实际的行为

无

### 系统信息

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 91.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.0 - ~/.nvm/versions/node/v18.20.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v18.20.0/bin/npm
    pnpm: 9.1.2 - ~/.nvm/versions/node/v18.20.0/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.5
  npmPackages:
    element-plus: ^2.7.3 => 2.7.3 
    plus-pro-components: ^0.1.8 => 0.1.8 
    vue: ^3.4.27 => 3.4.27
```

### 构建工具

Vite

**Comment by l-x-f** [comment]
[v0.1.9](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
