### ISSUE TITLE
PlusPage 中， PlusSearch和 PlusTable的columns 可以单独定义么？

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#167]
### 需要增强的组件/模块

PlusPage

### 描述

某些情况下，PlusSearch和PlusTable中使用的columns存在同一个字段，但是字段参数不一致

**Comment by l-x-f** [comment]
[详见](https://github.com/plus-pro-components/plus-pro-components/issues/94)
