### ISSUE TITLE
dialog 弹窗可以增加全屏按钮么？

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#169]
### 需要增强的组件/模块

dialog

### 描述

某些情况下，可能需要一个全屏的按钮，类似这种
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/f0ca58d6-3229-42b4-9a86-c2143e725edd)

**Comment by l-x-f** [comment]
功能容易实现，但是通用性不高，感谢建议。
