### ISSUE TITLE
建议 page 组件的 table-expand slot 增加数据传递

### ISSUE THREAD

**Issue by sanonz** [plus-pro-components/plus-pro-components#170]
### 需要增强的组件/模块

PlusPage

### 描述

目前使用 page 组件的 table-expand 插槽遇到拿不到 scoped 数据问题

```js
<PlusPage
  :columns="tableConfig"
  :request="getList"
>
   <template #table-expand="scoped">
     {{ scoped }}
   </template>
</PlusPage>
```

查看源码发现没透传，建议 [page](https://github.com/plus-pro-components/plus-pro-components/blob/dev/packages/components/page/src/index.vue#L72) 代码

```js
<template v-if="$slots['table-expand']" #expand>
  <slot name="table-expand" />
</template>
```

改为

```js
<template v-if="$slots['table-expand']" #expand="data">
  <slot name="table-expand" v-bind="data" />
</template>
```

**Comment by l-x-f** [comment]
感谢建议👍，可以尝试pr。

**Comment by sanonz** [comment]
这么效率，我准提 PR，代码 clone 下来准备加发现已经有了👍

**Comment by sanonz** [comment]
@l-x-f 啥时候发版本呀，等着用

**Comment by l-x-f** [comment]
@sanonz  本周四会发布新版本。

**Comment by sanonz** [comment]
> @sanonz 本周四会发布新版本。

OK

**Comment by l-x-f** [comment]
fixed [v0.1.13](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
