### ISSUE TITLE
table中，列设置全不勾选，然后拖动报错

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#171]
### plus-pro-components 版本

0.1.11

### vue 版本

最新

### element-plus 版本

最新

### 最小复现环境的链接

无

### 复现步骤

![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/cd655861-deb1-493f-bc91-cbe8522d68eb)

### 期望的行为

正常或者禁止拖动

### 实际的行为

报错了

### 构建工具

Vite

**Comment by nineaiyu** [comment]
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/9830bd99-6fcd-498f-ae8d-c8fc3bd5bf9d)

**Comment by nineaiyu** [comment]
还有个显示的问题，就是列设置，先随便一个不选中，然后点击全选，上面的全选显示不是 √ 还是横线
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/318e6ca4-b543-4c38-8d14-fdd631c334ea)

**Comment by l-x-f** [comment]
fixed [v0.1.13](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
