### ISSUE TITLE
在使用page组件的时候，table中，开启某个字段编辑，编辑之后，点击查看按钮，数据还是老数据

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#172]
### plus-pro-components 版本

0.1.11

### vue 版本

最新

### element-plus 版本

最新

### 最小复现环境的链接

无

### 复现步骤

![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/c254ec62-b4ba-4731-aae8-a311d46342a8)

这个按钮开启了可编辑，修改之后，点击查看，发现里面的数据还是老的数据，是是数据没有同步过去么？
是通过 https://plus-pro-components.com/components/page.html#%E5%A2%9E%E5%88%A0%E6%94%B9%E6%9F%A5-crud 这个文档配置的

### 期望的行为

编辑后的新数据

### 实际的行为

数据未发生变化

### 构建工具

Vite

**Comment by l-x-f** [comment]
表格中表单数据不会主动和表格数据同步，需要手动同步。
[参考文档-表格数据多级显示](https://plus-pro-components.com/components/table.html#%E6%95%B0%E6%8D%AE%E5%A4%9A%E7%BA%A7%E6%98%BE%E7%A4%BA)

**Comment by nineaiyu** [comment]
感谢，已经可以正常同步数据了
