### ISSUE TITLE
Search 组件中，搜索未检验配置的rules

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#173]
### 需要增强的组件/模块

PlusSearch

### 描述

能否和PlusForm一样，校验成功再执行 搜索请求？

**Comment by l-x-f** [comment]
根据团队成员讨论答复如下：
- 搜索是非强制的，一般都不需要校验。
- 特殊情况需要的，可以自行校验。

讨论结果是：**搜索组件暂时不增加校验。**

**Comment by nineaiyu** [comment]
在Search组件中，可以增加一个是否校验的配置参数么？这样也方便开发者灵活配置
