### ISSUE TITLE
table中，可否支持动态添加列字段？

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#174]
### 需要增强的组件/模块

PlusTable

### 描述

我尝试在table中columns使用计算属性进行设置，字段也可以正常展示，但是列设置中列全部未 未选状态，后期是否可支持列设置正常显示？
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/d78a4411-bbce-4b5a-a6ae-753bb3de225e)

**Comment by l-x-f** [comment]
fixed [v0.1.13](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
