### ISSUE TITLE
table性能问题

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#175]
### plus-pro-components 版本

0.1.11

### vue 版本

最新

### element-plus 版本

最新

### 最小复现环境的链接

无

### 复现步骤

当table每页10条的时候，点击编辑很快
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/0b20c939-6eb1-463e-b7da-ec651ffb2313)

当table每页100条的时候，点击编辑就有点慢了
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/1d892fc8-c4e8-4503-b210-2c7d2441089c)
下图是table每页500条
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/33523fd8-631c-4a99-9568-2e6eb1fa0455)

为什么点击编辑的时候，会跟整体表格每页多少有关系呢？是我定义的操作方式有问题么？

```vue
    <!-- 弹窗编辑 -->
    <PlusDialogForm
      v-model:visible="visible"
      v-model="form"
      :form="{
        columns: addOrEditColumns,
        labelPosition: 'right',
        rules: rules,
        labelWidth: 120
      }"
      :dialog="{
        title: dialogTitle + '用户组',
        width: '540px',
        top: '12vh',
        destroyOnClose: true,
        confirmLoading,
        draggable: true
      }"
      @confirm="handleSubmit"
      @cancel="handleCancel"
    />
```

按钮方法
```vue
// 按钮操作
const handleTableOption = ({ row, buttonRow }: ButtonsCallBackParams): void => {
  state.currentRow = { ...row };
  switch (buttonRow.code) {
    case "update":
      state.form = { ...row } as any;
      state.isCreate = false;
      state.visible = true;
      break;
    case "delete":
      state.isBatch = false;
      GroupServe.delete(row.pk);
      break;
    case "view":
      state.detailsVisible = true;
      break;
  }
};
```

### 期望的行为

点击编辑，能很快渲染出编辑页面

### 实际的行为

随着每页数量的增多，编辑按钮，弹窗越来越慢

### 构建工具

Vite

**Comment by l-x-f** [comment]
[参考](https://element-plus.org/zh-CN/component/table-v2.html)

**Comment by nineaiyu** [comment]
可能我没描述清楚，我的意思是直接使用el-table渲染500条数据，点击编辑页面很快，但是使用plustable的时候，渲染同样的数据，点击编辑页面就比较慢

**Comment by l-x-f** [comment]
PlusTable 中集成的功能较多，后期会优化性能。
