### ISSUE TITLE
pluspage 中 pagination 类型推理异常

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#178]
### plus-pro-components 版本

0.1.13

### vue 版本

最新

### element-plus 版本

最新

### 最小复现环境的链接

无

### 复现步骤

![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/68444388-77e9-4394-8bdd-b3cdc5c7b784)

### 期望的行为

正常

### 实际的行为

异常

### 构建工具

Vite

**Comment by l-x-f** [comment]
[v0.1.14](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
