### ISSUE TITLE
In a formal project, will there be multiple copies of Element Plus components used, resulting in a larger package size after the build?

### ISSUE THREAD

**Issue by oui-a11y** [plus-pro-components/plus-pro-components#182]
In a formal project, will there be multiple copies of Element Plus components used, resulting in a larger package size after the build?

**Comment by oui-a11y** [comment]
If only PlusDialogForm is used, why are there files similar to el-table in the dist folder?
<img width="1683" alt="image" src="https://github.com/user-attachments/assets/8c7a1b7c-5e06-4981-896f-b782a9c77017">
#

**Comment by l-x-f** [comment]
There won't be multiple copies

**Comment by l-x-f** [comment]
More information is needed to locate the issues in the image

**Comment by oui-a11y** [comment]
I used the plus-pro-components-demos project in the documentation, a subproject of the Vite-project. After using the build command, the files are over 800KB. I only used the PlusDatePicker component in the project. Why are the files so large? you can try.
<img width="950" alt="image" src="https://github.com/user-attachments/assets/c9cb5a0d-4e47-4bb2-b313-259352a7927a">

**Comment by oui-a11y** [comment]
I used the plus-pro-components-demos project in the documentation, a subproject of the Vite-project. After using the build command, the files are over 800KB. I only used the PlusDatePicker component in the project. Why are the files so large? you can try.
<img width="963" alt="image" src="https://github.com/user-attachments/assets/9d3b5643-8b87-42a5-a5c4-4809f354ada4">

**Comment by l-x-f** [comment]
fixed [v0.1.14](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)

![image](https://github.com/user-attachments/assets/a10c2ebf-40b3-4162-a8a1-ebef42f1f93e)
