### ISSUE TITLE
Search 搜索组件在 label-position 为 top 时的不稳定性

### ISSUE THREAD

**Issue by HaceraI** [plus-pro-components/plus-pro-components#186]
### plus-pro-components 版本

v0.1.13

### vue 版本

latest

### element-plus 版本

2.7.7

### 最小复现环境的链接

https://playground.plus-pro-components.com/#eNqtWN1O3EYUfhVrVWk30q63gaoXqwXRUi5SpSkC7rKRYuzZXYPXtuzxAkJISS+an6YhNwlpFQVFhaZNmxTSKEFcJC+Dd+Etes54bI//WKjYC7DnnPnOz3wznnPWS1/Zttz3SKlRalLSsw2FksmW0zIlqUmMmqo4Gn8NBlxbUUOF4NecNTx3TtF0S+rXepZGjIlWyVAWiTFruTrVLXOeAqjcVwyPtEpSw7Jx0M3X4kLQqyetgG3dtD1aM73eInEEW27XWrnGBhG9p5swdjkF0KxnfGd+zxPFUbuxnoCK7rRKsaihWobXY37zp4QUveC+pXwSlFjANZtHfGqe4llTalcxOwS04b9mkGn2mtBwWRiRBo9K1HCIS2ikMEdcGovDRLEkRSverCf4wIZc1dFtKhngAGBRXCaA9Wymofdsy6HSuuSQdhX+KCrV+0TakNqO1ZPKQLKyoEbXbAK6uAjTLJ2R4pQNYzXbsWqqBbomMalbR3U3Z/73AV/mrJWqNEdUy9EWUBBi5UAxEDab5VuakNaD8Dn1GgJmM4acvH4jUGPr05Bc6uhmB4c2wvSoMAmTk15SMBFmo8kGJitpk9fDtVgP5jek8lXSpuVqaK5s4Ku0Uc0qzumdrqjpsPdc1QXLFhQpvEnMe0m6wbUT5lh0l5LhxcxmYbWbAecnK+NpxSj0dhguDnkQbfnzMjdH9R5YM8mK9A1oVy7J1Jpnia0wtLRxvvEaAm2u3wAbPH3cjBTF6z/6efhyLzQmScAEG4ZNpUfiQRYyLjFIVMteiyXUsgyq44wAaPDslr/z6+Dpx+HO4ZdHB6/811vDv39naZKifGecGN5/P7h1O+NEkIx8N1xiEBXWNJRleSLYEW0Nnr06fvmb/+O/8dwIW8x78IN0Wg4yhmg8CPzFxCkw4n94e5qRy/lGFkF6HiuBiaOD1/lWxvKtrBHDsFbOFc3O/vG73Xwj42fKV/jID4hCIgy23p9svcsQAfdAPg002BM1W1eXiTOKZIPHeyd3NrNMZ5szH138nMYabZ0Y2izMBratAwxRdRe415DGqrB/CYCOhREXOuNvP/QPfsg4o+pU2FyJbae4qqKFbpyZ9QW0Dt04+eXx8e6n1BJ2dUNzCMQjgGaAE+C1FHyCpLuf/Df3svJCM7mmUubyDCbW+skeZvjBoUDC8CfS/cz2Ujs2k8e/nqLJi7OX2rtpe8PbzwcvdgvspYf4psuVC7LCY6Dg1IqovL9/ARy6fBqH/J1X/sPti+QQmBvFIX9v0z/cuqA1RXsjOORv7hwd7uCpcEH2RnDo6ODOYHtz8LwoxP9Lo7Oe9f4ztmHSRyDcp1XhsI8vGMf/fBi+/Th88ca/u3ey9cfw3gN/80PyOEyczLFLDLJrGXB8FuKE2iMP7rtwx9ku+E4RU1s406cq/1sSe4yXbz4Fv30OljPiasLNyKGz6bBObt0b/PSnqAcOFWmdOeDdJ/79/ewyOTos06hP7uajwd1H2bnEUaHOUCAmDoD/GF/ii6xYycH9tcJSCVlSzLVL0sRkaAyVLYPIhtXhKlX4WLJZ5eCCnIYMSr/zQgb1YwEkFosIWIRSjtUEhGY9KBZZaViqloKyrdZTbHnJtUzoN6wjUIsLoJREjrBEtkpw/e1BDmtYvqEA6lZKgUX1umfayx0ZqjmoVWOdqTF5XP6irukureumRlbltmcYcm8JZldD0JxasAg7rwINcJOQU6ITdR2zUoM6twi2QF30G+ED0pgbkDXqglJb76Ryhm7pBnF4pZrInYIX4G/ZGHU8Evmqdom6nDO+5K4G/s5ij8Dpg/eRDDZih0CnAMUz89fIKjxHQuiUeAaPtUAInIAiDX0M1L72kCnQE4n0mLdXGAWg6ltwZ1YpMfHCGTnK9yCLG5I1fUrosbvj8riQRTgl1jqOBca/U3QzbHfxZgZvYIR9BeiH8d6BXOe9sbLQ22DaWH3CsYauBOSI+g1yHnVg8QAifybUucJWMeEl7rpgSwbdgf5MohuD2ynfDIQVeQqZmPYcuD/QK7CXFVNNtWLCmLLBnNI6CSfNBETGuVxdpDbohUdInzi4mnB+lNkeFUQqNEUouaqby3i6APkso0+wcbQEtW9V6kLjgB85/MCB3kqgrFmqh8bkAII7UymjGI4gUMcn2SEG2nXpmkHcLiHQ0AhFCA4y/BeNKZo20wecq7AbiUkcwLMUDfol3LUYOKtJHMeCDx93nmlGTi5a2pqs2DZ8rio4HaTAy5ZpECrpuDSGQTRwpq0YLrBdWVF0iBRMz6PjSJB4aGY2GmyZZJWtRdszobcEOS5iWJBBvS1VInOXwFPqOQASppaJkCQTOcxBe4DA3zCYacuksOPxUfZcUsmYHTlDoFCsy1MR7HuWpXSQQmKCuIJAWA8JHOjpAJ0mU0wjiDZiXZZy5fN8CVTXDbgGTapiV6MFu3Bnb474JH62zvfehvh9Aa9vil6XNv4DQzXzlQ==

### 复现步骤

问题出现在 `label-position` 为 top时：
1、操作按钮位置置顶了
2、更改展示数量或更改网页大小，宽度受到影响

### 期望的行为

1、操作按钮位置应该与输入框处于对齐状态
2、更改展示数量或更改网页大小，因保证一致性

### 实际的行为

1、操作按钮位置置顶了
2、更改展示数量或更改网页大小，宽度受到影响

### 系统信息

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 32.03 GB / 63.79 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.3.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.22621.3527
```

### 构建工具

Vite

### 额外留言（可选）

![image](https://github.com/user-attachments/assets/521ea849-b35b-4170-a5f1-f42f94819f94)

![image](https://github.com/user-attachments/assets/03f1b052-2b52-4e7c-a5cf-356d97b4e3e2)

**Comment by l-x-f** [comment]
[v0.1.14](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
