### ISSUE TITLE
编辑功能需要一个隐藏的ID输入框传递值

### ISSUE THREAD

**Issue by Lin-Van** [plus-pro-components/plus-pro-components#187]
### 需要增强的组件/模块

PlusColumn

### 描述

hideInForm属性会整个输入框都消失，目前我能想到是下面这样，有什么更好的方式吗
``` tsx
 {
    hasLabel: false,
    prop: "id",
    valueType: "input",
    renderField: (value, onChange) => {
      return (
        <ElInput
          style="display:none;"
          modelValue={value as number}
          onChange={onChange}
        ></ElInput>
      );
    }
  }
```

**Comment by l-x-f** [comment]
这样做的场景和目的？是否是通用逻辑？

**Comment by Lin-Van** [comment]
> 这样做的场景和目的？是否是通用逻辑？

就是编辑时需要携带个ID 用于接口更新数据 一般都是放在表单里的隐藏Input

**Comment by l-x-f** [comment]
编辑时携带个ID 用于接口更新数据放在表单里的隐藏Input的做法并不是好的方式，页面中无缘无故多个Input反而影响性能。

**Comment by Lin-Van** [comment]
> 编辑时携带个ID 用于接口更新数据放在表单里的隐藏Input的做法并不是好的方式，页面中无缘无故多个Input反而影响性能。

这我不赞成 一个input能影响多少性能 id是最容易去更新的了 其他条件还得携带更多信息
