### ISSUE TITLE
可编辑表格是否支持数据重置功能？

### ISSUE THREAD

**Issue by yh3232692** [plus-pro-components/plus-pro-components#188]
开启表格行编辑功能时，修改了某些字段，请问是否支持数据重置功能？或者应该如何实现？

> 目前基于`formInstance`，通过调用`formInstance.value.resetFields()`，可以将表格内表单数据进行重置。
但是渲染在表格上的内容还是修改之后的（没有同步数据至tableData）。

感谢！

**Comment by l-x-f** [comment]
参考  #172

**Comment by yh3232692** [comment]
> 参考 #172

@l-x-f 感谢回复！

或许是我没有表达清楚。重新贴下步骤。
<img width="1443" alt="操作步骤" src="https://github.com/user-attachments/assets/4cc244ef-3b34-4382-a835-1bc67047f624">

1. 点击编辑，编辑单行
2. 修改应用
3. 此时不想编辑了，点击取消编辑

期望：点击取消编辑时，表格和表单数据重置为未修改之前状态。
举例说明：比如 初始状态下 appType = 1。修改appType = 2。点击取消编辑时，修改appType = 1

**Comment by l-x-f** [comment]
‘重置为未修改之前状态’  只需要保存之前的状态，重置赋值即可，不需要组件处理。

**Comment by Ttou** [comment]
@yh3232692 

```ts
const showEdit = ref([])
const editTableData = ref([])
const oldTableData = ref([])

// 点击取消时重置行数据，此处只展示核心逻辑
function onClickCancel({ index, formRefs, row }) {
  showEdit.value[index] = false
  Object.assign(row, oldTableData.value[index])

  formRefs.forEach((item) => {
    item.stopCellEdit()
  })
}

// 点击编辑时保存当前行数据，此处只展示核心逻辑
function onClickEdit({ row, formRefs, index }) {
  showEdit.value[index] = true
  editTableData.value[index] = row
  oldTableData.value[index] = cloneDeep(row)

  formRefs.forEach((item) => {
    item.startCellEdit()
  })
}

// 同步数据
function onFormChange({ value, prop, index }) {
  set(editTableData.value[index], prop, value)
}
```
