### ISSUE TITLE
It's going to rain.

### ISSUE THREAD

**Issue by protester16** [plus-pro-components/plus-pro-components#192]
### 需要增强的组件/模块

PlusForm

**Comment by l-x-f** [comment]
误触，已解，正常合理的需求都会满足，不合理的需求，过多的探讨没有意义。
“确实存在的需求“ 解决方案有很多种，不要仅仅为了满足需求采用不优雅的方案，多看看其他优秀前辈写的，加油。

**Comment by Lin-Van** [comment]
> 误触，已解，正常合理的需求都会满足，不合理的需求，过多的探讨没有意义。 “确实存在的需求“ 解决方案有很多种，不要仅仅为了满足需求采用不优雅的方案，多看看其他优秀前辈写的，加油。

知道了 谢谢您了
