### ISSUE TITLE
是否考虑在展开 收起的时候添加动画 

### ISSUE THREAD

**Issue by Li-0221** [plus-pro-components/plus-pro-components#194]
### 需要增强的组件/模块

PlusForm

### 描述

当搜索项目过多时 展开收起可能有些突兀 可以考虑添加 el-collapse-transition

**Comment by l-x-f** [comment]
release [v0.1.15](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
