### ISSUE TITLE
表格的columns 支持 传递ref类型 或者 暴露支持修改columns的函数

### ISSUE THREAD

**Issue by zmcode** [plus-pro-components/plus-pro-components#195]
### 需要增强的组件/模块

PlusTable

### 描述

Type 'PlusColumn[] | { [x: string]: any; label?: string | undefined; prop: string; width?: string | number | undefined; minWidth?: string | number | undefined; editable?: boolean | undefined; ... 30 more ...; fieldChildrenSlot?: ((option?: OptionsRow<...> | undefined) => any) | undefined; }[]' is not assignable to type 'PlusColumn[] | undefined'.ts(2322)

The expected type comes from property 'columns' which is declared here on type 'Partial<{ columns: PlusColumn[]; headerCellStyle: Partial<CSSProperties> | Partial<(data: { row: any[]; rowIndex: number; column: TableColumnCtx<any[]>; columnIndex: number; }) => CSSProperties>; ... 17 more ...; editable: boolean | ... 1 more ... | "dblclick"; }> & Omit<...> & Record<...>'

![image](https://github.com/user-attachments/assets/5b1c7825-ce22-42a1-a33f-579e0bab177f)
![image](https://github.com/user-attachments/assets/4649815f-0f48-469b-840c-2335aad19b76)

**Comment by zmcode** [comment]
某些场景下需要外层控制columns的变化, 并没有对应的方法和api

**Comment by l-x-f** [comment]
类型写法替换一下即可。
```ts
import type { Ref } from 'vue'
import type { PlusColumn } from 'plus-pro-components'

//  const columns = ref<PlusColumn[]>([])   类型替换为下面的写法
const columns: Ref<PlusColumn[]> = ref([])  
```
[参考vue 官方文档](https://cn.vuejs.org/guide/typescript/composition-api.html#typing-ref)， `ref` 也是同样的原因。

![image](https://github.com/user-attachments/assets/545d2892-d560-436f-9af0-38db4162b726)
