### ISSUE TITLE
在<PlusSearch /> <PlusDialogForm /> select  options 如何进行数据联动 

### ISSUE THREAD

**Issue by 15766365253** [plus-pro-components/plus-pro-components#196]
### 需要增强的组件/模块

<PlusSearch /> <PlusDialogForm />

### 描述

通过 computed 获取第一个的select的值之后发起请求渲染select的数据.

**Comment by l-x-f** [comment]
外面定义一个ref   ，watch第一个的select的值，外部异步函数获取到值赋值到ref ,  columns  里用 computed 返回ref 的value
