### ISSUE TITLE
搜索组件或者Page组件在搜索时在没有通过表单校验规则的情况下也会去搜索，而不会拦截

### ISSUE THREAD

**Issue by ymscora** [plus-pro-components/plus-pro-components#198]
### plus-pro-components 版本

0.1.14

### vue 版本

3.4.37

### element-plus 版本

2.8.0

### 最小复现环境的链接

https://playground.plus-pro-components.com/#eNqtGWuT1Mbxr0yuEq+O7Gl374HLWyxgk6NCyomvOPyJowqdNLurQyvJI+keWW/VgX0mEFzJhyQ4QFxQYHAoYzuJy2BD8J857a4/5S+ke2YkjVa6B1W+Klhp+t3T3dPT6k+96fv6ekSnmlPHQtrzHSOkx1fYikvIMctel4/wsuREwZLRockCIU3Tc6KeG7RWpkJj1aGnPLdtd1amFAxG34toEAJGh4Zv20GYg9rBjGkwC6BtwwloDhZQg5ndVj9bIoRFDg2yhYGCDqraFmUzPvN84NcndrDc9TaaJGQRrZIg3HJok/RJz2Ad222SSqPub5J6hQyATSq3llheS0w/Vss5hS8FJrP9kDiG20HTg5UpEtAw8jmG3fM9FpJwy6cgDp12inupStB5Z9y2ByLbzOuRig9AVHjG9IDIpW4YVJBF7cgRrsYRcrIEpRaFthOQ4SdfjV/uxNf/WYIyuvVh/PSzeOdpfGPnfy9uxA+vDD+98+Od7fHDy7v//WH0l89hUbzGH/919Mcv4i+vje/vSJnxn66Mtz8Y/u3q8N590g1DP2jWaiVCdHisGb4t9KkJav4jXdAnbduh57xfGaHx7tm3U7P3Nopbn3fgu77jGdZpYJTSU4f2gGYG2agUfbLoCPQqPL0VhaEHXl90zvTA8Yeg7lbJaWZ0EJpiQ2JwJPxnem4QEhnHpEWMYMs1iSYiBsKcbTWzPX6NpJEbhEYYBSea8MBst5Msu0aPTizygJ4mreMJsRDZJz5a0CKNKn9atn+Pb7N1jGvkXeXMQOmW0IO8/z7py+wQLEIvNBwAz9XVVWnIm4wZWzoarPWJQ91O2IW84RSDab1n+JpmQxZUie1adFPVD1ISAp+52TshttUUiNVsDdWTq6TVapE6OUEquFjRGfWpEWqz9WmSYPxSwhQGws4mWebe0gTeL8jctIITGh1VRgNlBJFp0iCopLwRMouQDYO5wCoPmUOIDfuHyxULEpwyVQ0I2g4Dfk3SqCvLDMpDwuY4ZzIL9HP6gmrBhh2a4NdE9dnUEVihAJ2XQIXA7oE5lSQB21EQNOo6j17Tcnny0dqCVZs3Xp9rGG/UF96YN+aN9sL8vFk3Z+Gt0Xi9sebTjo7/qUaENm6GSzcIZCbVVBeangWgi2rNTWIF4h4TOY1732BGL8jFQp7Aktgbhp1Sa4JqepIiiSLiQEQ2OamO/1WJrvMHtdbz0n9R1ToKQq8HzhIPFQgg7uUEQ9IOuFg1/nueeUnmAP7oUK9Cyniw5wyz20QTEUhee03GIvkZbB9i6uJ9WvWDtEecanktBDeer8CL/6ac8O1wfCbSD0NoLyOxYkgjE3sTQxMuhfQWQXosqzZHRAkCjWWUt1QYbCsAZ0hDbqyiQ61GRk+uxS93ZuXBLeIBo28JCo4dUA0SynPWoaIpHofz9ByEqReFmpYvOGgzx9cqlTSOBlWohvW6fFd9kEYWRlEzdQZUTlEZkgaBl7tm5iFRBoWzU4/LWpr1OlDw0wP+/AXw8HkhNdXWMVYpsK3Ef/549OjrLAtDz3NC208hwzvb8YNbw09ejh58f3T32eP4yc3RFw8z/A3bwqLcgJqfLGGnA/RZpUx5C/1QJ3AxVA/VeQE0Re+sU9Z2vI1ziRJZ+GTJIuUULBld/3a4ffkwmom8yDDXDSei5+BYRxgUMjPMYJ4f2uDcZuJA/MvVlUT88M7j8aP78Uf/USua5A3gen4ZGlSPwTKjFj/GZfFQcEqFxE//vZ+QRrmQVYC+ihQhYvfZk3Ips+VStqgDW/dK1jz41/ibz8qFzB3KX8njhQNiY3j36ujJy8PEBpzV5YGRA7Rt6lgyhjWpsuiXijVBpjm2jU3BMdP7oJgeXns0vndj/MPt+PtizkFhmdQ+aQPKTShCy+xwo94qZZN2qEdnYb9Ex5A/CE+AzUlzVKGbJuWJBNeaPFrikuNkYR/6tCfak3puH+q01ypQ76NiYQvR9sPu2+7z+6O7l+N/3Cxu2kJh07C3yfC6cFs84y7zS6Y8A8r2khMdoMX4qw/jP3x0mLjBPrE8ZvKQfZSjls3ru1q099QsfrEd7yhFLMnHomaiO31l90ySvZp2t1+Orl3NiKUq0Pfuq/EhVcuxYRS6FnYa01DkX5V47qku9ve5fgu6lfHVx/GXt3a/u7b77Prui7uTqQk0lkN/DV35WTHayC6C4r6LnBcZ8xg+LIuUIIMmMdytyWSHoxruahPtc0qkIbdcpzwgpgHuJhpF/pJlgZwLFyh56twkRTaWIGKizhcSsqslt+KqejrDRmjJ3doIUJfqpC4BM2XlyB0yuNN03aYby8zEXgsOfY50YQJLzmw4bPLCAIVnckkJl8pRGO7kT7bkT8x/ztqdLsjlQyDloCt1lSxhubWBemlCT+QJ0jlEfrmgsmFiJQQ9irrivU9GWLMYdAX0JJohKEQwinY3m54UY0+N6lUjoEfn09tabm7DWenM2MBt5qyKXDBvvv4ABktqphEYQyV6kfj2p4AxvH493n4BaTV6/vfxvc9h+lTklZBoQqmCtMmb4IQvxHUBYzOZAImVyujKd/HV5yKrs5sD/ikvF7IrxUE9w81vf7z5TaF64eW6vMSDG+mMb5uX1JGCKGanPQbXV6Vk4g9vtrJbB599wg5JRcRE5XwfHP5eZEO/JujJgJNxBsdqYlDJx5JT1Skx6JqBeY6+FnguDHz7yGlFAmCMiTcFrtbKlDomQ8DKVDKJiFz/UkfMHxSck7P6nD4PY9MgrPErot6OHEfvrQF1NWFaMvjbi3fZjFDwzbM8qSpRs9FXMzC024vtHuiq3shebII7AK+FASDBVW/CZ6gW5AJ7R1xccr4zsEP/DV8Tx5NcN7vUvFSyvhZsCn2XoG2kbB20T2Eh1CsKU3MELy7/jm7CcwrseRZExb7As3hZhuGq5wq0tyIsJUzB49qe4SEAvd+5YHEzpG6QGMWDUuQBtxucdWof0zN15/Q5xYtLjrHVYR4I/61hu8n3BjlIl8PzZBILHyTk9FWvyY8TFWVMy7H5xwjmoSoiONKJrV46q16DWa9bTqlNq6niwks28cdPAagOfBfIfQnAdCoXA2almoInTkUMKmJ4BjLYcM1sCp2zqWjMPt8HEqJFEchIWzrZBkNE4YDLPu4mlI4Kz1EFZDIYvcI8xL0E0GQOU4WSsgaX8yrpMtqW50Y6TXIEsuWZEQrTBQupjFZBMBRXQMcnGO7i0BkmAXCSB11KQxAuQcgcYPiTrhmWtbgOfLAroC4MqCp4fFVQI65axriIyRsejorKc8xUyVXP2tIN34ezSUNygEJcrrgODWGeBVvjONQCZcSczRWHIIpeRsUxQLKlxaV0ccWlm3wv2pHLT/I9YhMOIO5BHPyl4qZlf5W5loMwSFolkYPygIN8Q2NgAhVCxuOjHsEYrSD2QAolhDJc6QqR99xLk0YqjhF2yUZRnelNBlMWRmBtGnXFkEvn3Yc5CUy4bHLFYeC3t6rphv3kyl484Ej8eV/m3kA9X0Dri6rWU4P/A0axzLU=

### 复现步骤

对于需要表单验证的search组件，并没有去调用form的validate方法，而是直接调用父组件的search方法，导致表单验证没有通过的情况下，也会直接搜索

### 期望的行为

能够在表单校验规则没通过的情况下不去查询

### 实际的行为

实际不管有没有通过，都会搜索

### 构建工具

Vite

### 额外留言（可选）

这边是看源码和demo看到的效果
Form组件通过defineExpose暴露了handleSubmit方法，但Search组件中却没有去用这个handleSubmit方法，而是直接emit('search')了，这样导致，根本没有去调用form的validate方法

**Comment by l-x-f** [comment]
大部分的搜索都是不需要检验的，但也是也有少部分的特殊情况需要检验，下个版本增加可选的检验参数。

**Comment by ymscora** [comment]
OK，了解

**Comment by l-x-f** [comment]
release [v0.1.15](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
