### ISSUE TITLE
表格组件是否支持列排序，如何设置

### ISSUE THREAD

**Issue by netty2019** [plus-pro-components/plus-pro-components#199]
### 需要增强的组件/模块

PlusTable

### 描述

表格组件是否支持列排序，如何设置
![image](https://github.com/user-attachments/assets/e38918e6-8b5c-4bb1-924c-135fa4d893ee)

**Comment by l-x-f** [comment]
支持的，兼容element-plus组件的功能。

```ts
import type { PlusColumn } from 'plus-pro-components'

const tableConfig: PlusColumn[] = [
  {
    label: '名称',
    prop: 'name',
    disabledHeaderFilter: true,  
    tableColumnProps: {
      sortable : true     
    }
  }
]
```
[完整示例](https://playground.plus-pro-components.com/#eNqtV91vG0UQ/1dWFugcEZ9pzZMVl5YQRFGBqMlbXambu7FzyXrvtLvnxLIiwQtISEi89YUHJECVkCrxURWe+GvoB/8FM7t7X/Y5IVLz4r35/M3szOxk2bmTZeE8h86ws2Nglglu4NZYjSVjO3Ey90f82Be5PuRHAtgwSkU+k3o07hgi7KZykkzHHTa0n72YG17wPsQzcvqFyX5hc6ff8GZJOlJJZpjgckr6GhU1mDyzEsksS5VhS5ZrcDgu2ESlMxZkiKyXqbQXpSgjQRod1DTMIgNUI/y7FviVilZZGlATHgGzzu6nZ2zpYkjiIZP57AiU+5Z8BkOmjUrk1FG04SbXTZrh0xVCQmqYH6Dvi8JvlEpt2CFocwBqDmxUuJ2CuZdoM2RcL2TEultsdKvgMebUKPOocUcpvggpxu6SCZBTczxkA3axFc541u0mmPltlsgYzptGGFOYbiXrFBevFd6uU13Uls7eYQF9Bg2BIgkHNuauk3ybDbYaUjYtjjcajdgN9j4LdB5FoHXA6pybxDnjCi9m2uQMiJPISUrkIMbiAdWE4lIt4cymu7tV8Wza7aEkrqeAsjp0ueW6LIcHD0tdd7A/K/e4xAB9F2DVjcra3ams3HJ4Kp1aTw1rVfvgIeo/cK5KcIIfgcCoX3z37asnv1ZRY1FnSG7eSpxoMh1/DDwG9VEisMKHzKgcthkrhLx38riPRvACa5nQ2E9uBFg1S1vNgne3BvHVN89ffvHlGkRXJhV5zkUOh9iyxAMBkal4aWYSTNGwSAP9NUq18PXy+19eP/nxxVd/NOvA2kb2u00yjrMUExEoiG37+9KoybQ6efHn75c5udHu5Ai51/HiXPzz19N2LzfbvSxAiPTsWtH89NvrZz+3Oxn8r3wVR98XGwvh5Q9fv3r691oh4CRor4IGY5KAiH1hdj0+N1U3jTI7/4fOYq3frwL5+Pm/j5+tg8RJ0o4SxwP0siQ6xeFTmwc2GVVv+yGOndwyxY1arA70pRs7NDr4GU9qD0PoTVXTrJw0oYt1ZHU9FhZxEx2zLiiVqi22rIZVw85O373B9sXtbHfcE9rDZyM80anEJWFJ5saegS80zQfrftzBbp3hG9qjZ5UY486xMXhR/X4us9NpiK9svy5z+2Y4CN/DjUCbvh3n4SQXIpydoPZ2YbTljd5ku0XU222avF0H0U8o0z3cgDaZ3SBex03m3ZXLC8ya0SiE43slZwQrEaA+d2OskTtO/fqJpdmBXNCjY4hOW+gn+tzh3VegqR5q8Rmu8FIde+/gMzjHc8mcpXEufKwbmPdB4/wnjE7sg1zGCLsmZ9HetSWAnXeo984NSF0ERUB9c9m4MVm7l4RewR2Eg1oW9wVfTFWKzj/liSx2VL8j+r2w2PFwifU7Xdj3C21QWxmtND2lODkIiiuOcg8M20oHLw9NtGtis9RaReJHtczSlktwcOVtLLnUTu1uMKwSKWZiN1cKOXex/7nE/bNA2YhpPZhLVtpCac8VMul68Xppo1wxpuag6DZxhAS2R2usSAGGcy+Rp8jtYvGlYo77g4ITfKq32bGCiZ9pmAinIpxwnEY5OQudCQ+mGxA7wITi8MVTqECQX20WAvQxgEHnnkXGkUc/JY3H8d4c7dAMAwkK7aU8DgiRhVYZXpe0w9CKEngrWYI8SuNFyLMMZNwldeRiXY6lAIO7J16NwE0KwUy40FjtbjqT6wMCTgVSkfb2S+JYwrm9i0kuI+qFDbWJD4PNYDJhuDp7d1v+UatSa1lUJKOWyiF/aMF/UTC4VRrseDqGuIp219xeqVEroUrWp8L1vc3SapC1xLi4/OtMOzkCmCVoerWYqjLCaMuqWy+54DovQYT/V1jguPBvhlpe2BsH++iKJ/Gtpe+9i/r7gqgf1VF3Lv4DAWNUhw==)
