### ISSUE TITLE
非I18n版本

### ISSUE THREAD

**Issue by simple-hui** [plus-pro-components/plus-pro-components#202]
### 需要增强的组件/模块

PlusForm

### 描述

能否开一个非i18n版本？

**Comment by l-x-f** [comment]
暂无计划。

**Comment by jackzhang0504** [comment]
国际化版本，切换后PlusTable，Form 的label 都不能动态切换

**Comment by l-x-f** [comment]
@jackzhang0504  请新开一个issues，并提供可复现的代码链接。

**Comment by countryMan1993** [comment]
@jackzhang0504 需要通过计算属性动态的写label 
<img width="713" alt="image" src="https://github.com/user-attachments/assets/90a07896-360f-4882-a205-6ba996538544">
