### ISSUE TITLE
搜索组件中有依赖异步数据的组件时【例如下拉框】，每次展开时都会重新加载，重新获取option，这不太合理

### ISSUE THREAD

**Issue by fauk968** [plus-pro-components/plus-pro-components#207]
### 需要增强的组件/模块

PlusSearch

### 描述

搜索组件中有依赖异步数据的组件时【例如下拉框】，每次展开时都会重新加载，重新获取option，这不太合理，期望能有只是简单的css展开或折叠，而不是每次张开折叠都要重新渲染

**Comment by l-x-f** [comment]
建议的写法
外面定义一个ref   ，外部异步函数获取到值赋值到ref ,  columns  里用 computed 返回ref 的value

**Comment by fauk968** [comment]
> 建议的写法 外面定义一个ref ，外部异步函数获取到值赋值到ref , columns 里用 computed 返回ref 的value

好的我试试

**Comment by fauk968** [comment]
solved
