### ISSUE TITLE
表格相关功能建议

### ISSUE THREAD

**Issue by wbsllm** [plus-pro-components/plus-pro-components#208]
### 需要增强的组件/模块

PlusTable,PlusPage

### 描述

场景: 一个普通的数据列表页面, 顶部-搜索栏, 下方-表格; 期望: 表格可以自适应高度撑满下方区域高度
期望表格可以添加一个字段-key:adaptive, value: 布尔值, adaptive为true,则自适应撑满高度;
其他相关: 撑满内容区自适应高度相关配置- adaptiveConfig--一个对象,可以配置以下相关字段:
表格距离页面底部的偏移量-offsetBottom;
是否固定表头-fixHeader;
页面 `resize` 时的防抖时间-timeout;
表头的 `z-index`-zIndex;
参考的pure中设置

**Comment by l-x-f** [comment]
经团队成员讨论已列为计划，确定下个版本增加此功能。

**Comment by l-x-f** [comment]
release [v0.1.17](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)

**Comment by xliyq** [comment]
功能缺少暴露setAdapive，展开/收起搜索没法再次调用setAdapive
