### ISSUE TITLE
建议添加一个 FormDesc 描述表单

### ISSUE THREAD

**Issue by sosovia** [plus-pro-components/plus-pro-components#210]
### 需要增强的组件/模块

PlusForm、PlusDescriptions 

### 描述

效果图如下
![image](https://github.com/user-attachments/assets/1b2f2038-3796-4f88-aa4c-10fcca183a1d)

代码类似；
![image](https://github.com/user-attachments/assets/7fd1457b-da24-4484-a078-f1f4b1addc72)

是的。相当于form 表单包含 ElDescriptions ，但是可以实现form的 rules 校验。目前的 PlusDescriptions 不支持form 校验 和提交

**Comment by l-x-f** [comment]
已列为计划，下个版本就会增加此功能。

**Comment by l-x-f** [comment]
release [v0.1.17](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
