### ISSUE TITLE
PlusSearch组件的hideInForm属性不起作用

### ISSUE THREAD

**Issue by fauk968** [plus-pro-components/plus-pro-components#212]
### plus-pro-components 版本

0.1.16

### vue 版本

3.4.38

### element-plus 版本

2.80

### 最小复现环境的链接

在下方复现步骤中

### 复现步骤

`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/element-plus/dist/index.css" />
  
  <script src="https://cdn.jsdelivr.net/npm/vue@3"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/element-plus"></script>

  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/plus-pro-components/index.css" />
  
  <script src="https://cdn.jsdelivr.net/npm/plus-pro-components"></script>
</head>

<body>
  <div id="app">
    <el-card>
      <plus-search v-model="state" :columns="columns" />
    </el-card>
  </div>

  <script>
    const { createApp, ref, reactive, watch, computed } = Vue
    const App = {
      setup() {
        const state = reactive({
          status: '1',
          name: ''
        })

        const columns = ref([
          {
            label: '名称',
            width: 120,
            prop: 'name',
            valueType: 'copy',
            tooltip: '名称最多显示6个字符'
          },
          {
            label: '名称1',
            width: 120,
            prop: 'name',
            valueType: 'copy',
            tooltip: '名称最多显示6个字符',
            hideInForm: computed(() => state.status === '0')
          },
          {
            label: '状态',
            width: 120,
            prop: 'status',
            valueType: 'select',
            options: [
              {
                label: '未解决',
                value: '0',
                color: 'red'
              },
              {
                label: '已解决',
                value: '1',
                color: 'blue'
              }
            ]
          }
        ])

        watch(state, val => {
          if (val.status === '0') {
            columns.value[0].fieldProps = {
              disabled: true
            }
          } else {
            columns.value[0].fieldProps = {
              disabled: false
            }
          }
          console.log(columns.value)
        })

        return {
          state,
          columns
        }
      }
    }
    const app = createApp(App)
    app.use(ElementPlus)
    app.use(PlusProComponents)
    app.mount('#app')
  </script>
</body>

</html>`

### 期望的行为

名称1的hideInForm属性生效，在state.status===“0”的时候隐藏

### 实际的行为

名称1的hideInForm属性不生效

### 构建工具

Vite

**Comment by l-x-f** [comment]
![image](https://github.com/user-attachments/assets/ad60e5d7-c4c1-4910-a0f7-525950f2da78)

**Comment by fauk968** [comment]
谢谢大哥
