### ISSUE TITLE
PlusPage 动态调整表格字段时，搜索框动画导致页面布局跳动

### ISSUE THREAD

**Issue by gltjk** [plus-pro-components/plus-pro-components#214]
### plus-pro-components 版本

0.1.16

### vue 版本

3.5.8

### element-plus 版本

2.8.3

### 最小复现环境的链接

https://playground.plus-pro-components.com/#eNqtVl9vG0UQ/yorC8lnyT4jwpOVRIUoSEUFopa3ulI3d2PnkvXesbvnOFiWEIoooBBKBS8VVZUoQvASQIUUkiK+TC5OnvgKzOydz+fYboXEU9Yzs7/5zZ/9Xfqlt6LI7cZQapQWDXQiwQ0sNyVjixsLy5c/Px8eHJ///eTq4PerJ4fJ8V/J6Q+XJ8+So6eXxz+xNd4GNny8e/Hw++FvhxcHnyWP9rLz3hdXj46To93z0/3zPz65PNhbrCPeCHe4e5I83B9++mfy4Izd5n4QsuTzBxdfHf7zYu/8xePk62+G+7+kOYdnu+dnJ8mv3w2PTsn+7dPL58+SL38c462JWKcY3Von9EEsNUutAISvmyXWCCMThFKjLTuhUQcfAxoEV23An/Uxjq2o4YUi7tg72YmAFHwUgzZo5HpHesypsKVl5vSZzw1vsLv3qsyEhosGe50NKnQj0DWPK5/ocKFHmRbrhTbjT+2pIDJMg4kjtASdKFSG9ZkXdqLYgF9lClpswFoq7LAyTqpcCBpxrtpT2oVRaISWWqTCGiGFEqTReLUpPWyCYVyId2yT2BK7S/X3GcZGDVbm5SoTfB2wEjyzQXXCu17wrk95vYLXQ29T3hunzAYwTphnYVz6jJC7XMRAlgL0ZBRlyKOmUqRzxwzYM4dQKmNfNkt0jlrrpDPMW+G2AmFAOT2yplCuzeUG0hOxD9rpuVRppYK4i/V0dDi0UrWUjqTW4ZG7qUOJz6lP9JuZA1eowayFbCCgg/Oo0YjI0SxtGBPpRr0ey2ir7SLBejHmxhvugvtm3Q+0qQfSh57bioVwO5t423aJQGfMex72jNAMdxLyRpFEPaA+1nAD58HOCS/yJnhCx7ENsGtGY1AraF/rGdEKBKgPRk+20DucVrj9rrUZFUPO1dsAb2uGfVP3Ur5rCjSoLrLPfYYUwKTu1TvvQw/PuRO1JBZZrXOct0HjUhHHNOztWPpIuxBn2d60KxDI9od6tWdA6lFRRNR2w8Y3S9islZeUPqa74C4Uurgm+E5bhZj8PR7IkZrPFhaU+0wf3Hom/UVBsdFWVVRIVNLlyDXFnbU6ODyEmH3TmXwo+GPyI0N0plQRS5qdBsvKmWInVmKl0HMTXzeXHswWyeliXiaP2aXVdJHpbhZeXO2CjHZB0TRRVMr2jRZcngIs51Ygt9Dr4PKFootCrWATPFNlGyhRVn7seNMrIg32Qy+mZG4KkZFxyuQmRWM20FUgKK82OwL0BoDB5JmLwNFHf3Ib9/3VLuLcwtcIEmWuLELuo5xm1MbA05GgVKhsKJG3kTnJ9dDfcXkUgfQduo5e3MumFGBYQKMRAnwkk34EJd/mAVaKqe8QcVqQsWl1LTc2JfTsLFqx9OgtzNlN1HDbwaDFnDxdBZmaWCHIqLXWRUuyNGNzKB8iZL+omJVQGnzxdHRjDc5U2lfeKKzQODZrRfrubZeuF1loTFpXWgiTsM2QQCdA6OvLNF4jrDbfuumVK/+XL4Gndbpr+M/MfKr5wP53svdf8Ul8rZ+9vUHx+4Ks7xdZlwb/AvKo9kE=

### 复现步骤

1. 确保页面宽度足够让 Page 的搜索框和搜索按钮处于一行
2. 点击 Radio，在「a and b」和「a and c」之间互相切换

### 期望的行为

搜索区里b和c的搜索框互相切换，重置与搜索按钮始终保持与搜索框再同一行。

### 实际的行为

待消失的搜索框的淡出动画与待出现的搜索框的淡入动画同时进行，导致重置与搜索按钮被临时挤到了下一行 ，等动画停止后才恢复到与搜索框同一行，即页面布局发生了「跳动」。

### 构建工具

Vite

**Comment by l-x-f** [comment]
去除动画即可。`collapseTransition: false`
[参考](https://playground.plus-pro-components.com/#eNqtVl9vG0UQ/yorC8lnyT4jwpOVVIUoSEUForZvdaVu7sb2Jeu9Y3fPcbAsIRRRQCGUCl4qqipRhOAlgAopJEV8mVycPPEVmNk7ny+x3QqpT96bmf3Nb/6uB6V3osjtxVBqlBYNdCPBDVxrSsYWOwvXzn95Pto7PP3nycXeHxdP9pPDv5PjH8+PniUHT88Pf2arvA1s9Hj77OEPo9/3z/Y+Tx7tZOedLy8eHSYH26fHu6d/fnq+t7NYR7wx7mj7KHm4O/rsr+TBCbvF/SBkyRcPzr7e//fFzumLx8k33452f019jk62T0+Okt++Hx0ck/y7p+fPnyVf/TTBWxWxTjF6tW7og1hqlloBCF83S6wRRiYIpUZZdkKhDj4BFAiu2oCf9QmOjYg1NHDlddBk4IVC8EjDHcWlDgig0eJCwxDvsQZq464Fz07kUcHHMWiDQq63pMecClu6xpwB87nhDXb3XpWZ0HDRYG+yYYVuBLrmceUTb8LOKC3WC/XAT+2pIDJMg4kjlATdKFSGDZgXdqPYgF9lClpsyFoq7LIylrRcMBoHV7WnNF1j0wgltUiFNUIKJUij8WpTepgtw7gQ79lssiV2lxI1YGgbNViZl6tM8DXASPDMhtVL2rWCdm1K6xW0Hmqb8t7EZVapicPcC+PSZ4Tc4yIGkhSgL1uRh9xqykXaIOgBc+YQSmWiy2qJynFqnbSGeSrcViAMKKdP0hTKtb7cQHoi9kE7fZcirVQQd7Gelg6LVqqW0pLUujxy13Uoce4GRL+ZKbCFGsxKSAYCuliPGpWIFM1Sx5hIN+r1WEYbbRcJ1os2199yF9y3636gTT2QPvTdViyE213H2zZLBDqj3vOwZ5hmuJchrxdJ1APKYw07cB7sHPMib4IndCzbELNmNBq1gvaVnBGtQID6aDzbhdxhtcLN963MqBhyrl4HvI0Z8nXdT/muKtCgesg+1xlaFSZVr9z+EPp4zpW4dGKRxTpHeQs0NhVxTM3ejaWPtAt2lu0N2wKBbN/RK30DuHGyoIiozYa1b5YwWcsvCX1Cd8FdKGRxVfCttgrR+Qc8kOO1P3ux4LuQ7Qe3nr0RxYVire1WUSFRSZsj3ynurNbB4iHE7JvO5UHBj8uvEdGZ2ooY0mw3GFbOFDOxHCuFmhs43Vx6MHtJTgfzsvWYXVpJG5nuZubF1i6s0R4oqiYulbKd0YLKU4Dh3AzkBmodbL5Q9HBRK1gHz1RZB1eUXT+2vOkVkRr7oReTMzeFyMg4ZVLTRmPW0FUgyK82WwJ0B8Cg80xF4Kijn1zGfX+lhzg3cRpB4pori5D7uE4zahPgaUtQKlTWlMhby5zkWuhvuTyKQPoOXUct9mVTCjAsoNIIAT6SSR9ByTd5gJGi69tEnBpkIlpZzYVNCX1bi1YsPZqFOb2JO9xmMGgxJ3dXQaYmVggyTq1VUZMszegc8ocI2RcFsxxKgxNPRzfW4Ey5feWNQgtNbLNUpHNvs3Q1yEJi0rjSQJiETYYEugFCX22mSRthtHnXTbdc+f+8BJ7Waa/hn5n5VPOCvXay91/xJL4xyGZvWHxfkPX9IuvS8D/luAVU)
