### ISSUE TITLE
table组件中index列的序号值无法自定义

### ISSUE THREAD

**Issue by yangbocheng** [plus-pro-components/plus-pro-components#216]
大佬好，我试图将table的index通过自定义每页重新从1开始，而不是默认的按页累加数值。
当使用了文档中的index-table-column-props绑定时，发现没有自定义的效果，该怎么解决呢？
如下 index函数，和 formatter函数都没有触发
![image](https://github.com/user-attachments/assets/40bb5949-8159-440d-8f78-82ad1a4c95dc)
![image](https://github.com/user-attachments/assets/2cd8603a-2f54-426e-aad1-9f78099e76d1)
![image](https://github.com/user-attachments/assets/40414b44-8e08-47e3-985d-65006356d3ab)

**Comment by l-x-f** [comment]
确认是bug,现版本可以使用`render`函数自定义。
[示例](https://playground.plus-pro-components.com/#eNqtWGtv40QX/iujiFdJXhonbV/eD1FbFrpFArFQ0RUS2lTs1Jmk3nVsMx73Qom0SNwvAokPfEFiEawQSIirWASIX0O75V/wnBmPPXEcdoGt1Naec+bMM+c8c+YcnzQeSRLvIBONfmNNiUkSciU2BhFja8PgQD/gcTvM0st8LxTmnTEpRuuDRmKHH49SxSNfDBpWoe/HYTaJUmgp0tiMo1EwduR6tDPkiluVi3h2FQIFhT0uIR/xMHWNJ3wcRFwFcQThiR1mTMWKh0vl+yQeivBZHmaizzAHOEexlU5LexdKe5v7PBoLWMX/YSi2KwI7p2tc1DU+Wus6nsNr6ssgUSzEDNpcOmiwVKgsgTSYJLFUTB0ngp0w8uumdtQSw1IaH56qbmVTNpLxhDXJ4Z1Exh0/hp1IRCptFjZPWJYKPe9e9RHFQhUUgAjCSAk54lhUm3omPmTawcGwz6JssickvUV8ApemSgbRmN6BU2WpOyLhDXdGehgof7/P9uI4FBwLIVrBrBHFx+XrlMD4MTwAoAU/lvIQF9EE/vVi32sW8pXdjVa7NDDHU8zB3ktaF+MvAXEYbrTor2PgskjVjpAHNFF7YyzUk0Gq+oynx5HPWm22vmEkjFnQBNEA3QlepJisF6i9A+Kkq04HAQqPSMmPPYpI64SFIhoruGy5x6Ztb8KTVisA0ZZY4C5nLQTRUBzla+gF/8ta9Mw6bLnNHmQBfpdpS/YEq0xGpRETYW3EOUAmzsb0GlthD7Nmk9mBB1mT5E1H3/JgR0exZfT+w1bbjo5hhhFtsFXYXIHJVe8h107OFmtgha2vr7MedJXMBNR1RnAmGC7NAY3EIQNvRMsFoHmWuwtWl0k5zXxfpGm5OZJoM4dc4lCMZyWEuhkgkjTcxMGxOUU/TDV1ioRkoo3QLPd6PSux/teR75v487Q4dFd2jTH8cU6Ck0odCpsMQpy/QlPykIZ8T4QAd/rze6fv3bZBQjJICHH+ehgMiWHN//eSIzsmBbYpW88vAZzZ8bRd8iTHffWBE0uC5enVfNsasLZSxfD+u3c+/6aCweVOjmN5pZcPjGI52YYeuFQs3e2ys9u/nL518+zmJ398+U6BKAuFq2ZZq51hfxyp2cULWSAFGE98crihbw0QAQcHEM+/vn3+2wenr97KN+Dq5bGmn91q/Bc64s5bP57deLniCHNo7KAmy2XcDyQRofCVlcQJXUTYarEzZ1d2hbOPvjz//NPT1753j6W2CWHPHcQNHUsMwg0lgQt5jenT298tNr1cZ3oPsnuzbQz//tNXdbZX6mwfizCMD+8R+Wffnv9wq8706l09Yh527wcvbXb8x8xEVh2PBUH0dTnigp9j7h833jx7+4uccf+auedfv3L6xmuV87rSs+c1pzLl9joi6/GFts9uvn7nq9/uZhtpu840DS9OPL/eOH214KvNMlXL5rapPYBGshj5h7fOPvq4cp7pLqozhhwvOkngXxeyuteHirwXiHBYJRhVi/n8MuKoN32xH4fI1W68ZxEZwnIUKs3n8NO5dKlz8WIp1Ogeq9HI2XA/SG9u5vuTjGe2+LcoPYh2nXouL99wh87Vb0oeVws5fTdT+cYPeeAUg15uhkpNU1fkVWpx4dNMXbhR3UZLoKrzPE+/Tdt62pT5HBRjLSFlLHHRmhvfMW1B13ckWKX1vK0r+0UX0e6zgzgYFtuarTwxqZhjChJnPay+1jUtDBqWxlLD9Asd7MO7lsYROkVtcpAL0N4UAR80cGNN0Gd0qOYmAToppcCcbjeLkutjD51I19W5sOKtev9DI5Wqrq4ovBFqb29yDbNzKphGs9LHLLJdo5rbnTV5wQXRDcjFHfRAi8wuUHdxk3lbssFrKoUSCrWKzwhWEAr5tLnMZ3zH6UZ7Qo85JwFz9oV/vWb8Wnpk8G5LkRIjnf0pLhFTI97aeUoc4bkQoi/GOf1L4TMiRVlJGI3aoxmxTzp6Gu3jmgKojy+nW0dKRKndFAEt0+agAWdt/sXWS7ir3qrjxe2QH49ljMUv8SCyHyryBrvSVONLRt7Met38q4bb7WptqpeRygiKIUfRAHt11EHwYKJ+Jp0V56DgZfb7CcGh7wQzXwewpfplsK0CKTyxmUnU4WruC8DMnuY3cw9t/5YhMs3N1V1q628AJt8cCEnRRK5o6jPqiHwpsJ0ng+g6pR+QLw4P0OtKcQ3l6hLbR2dSZlQzJTTKw9jPaDHPmMjBtJokbuqESE+eFCGtm6pjXCf7Qiid7bWIjENG/4oxPhxuHcAOpTARoXlphjEfNgmRhlYantfUeVerEnitWYDci4fHHk8SdEQtmm6y4yAKBfXbCE0YCuRY040OInM/0NI7BJwIUg5tbReDg0gc6ViMssins7CAm7iWzLeXEUMrnS/Xzluw0rVaZL5qzDPHXE5WhTaD/lHhxNOjhy8nrbll7zrDoVCpm7vCnHvtpeomHceYfeW9JDXpADAJYLpKppkPKwXr5inX/Ds3gY9G31y+NqB1UIuA3XewV+9yJT5wkp+9qXu/APVVF3Vj+idQLySd)

**Comment by l-x-f** [comment]
fixed [v0.1.17](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
