### ISSUE TITLE
PlusTable组件，期望在columns配置添加children属性，支持通过columns配置渲染多级表头

### ISSUE THREAD

**Issue by pengpengjed** [plus-pro-components/plus-pro-components#217]
### 需要增强的组件/模块

PlusTable

### 描述

功能背景： 当前组件仅支持通过模板渲染多级表头，但有些场景需要通过后端接口返回的数据动态生成表格，并且希望能够通过配置 columns 属性来定义子表头，而不需要在模板中手动写入多级表头。
`const columns = [
  {
    label: 'Date',
    prop: 'date',
    width: 150
  },
  {
    label: 'Delivery Info',
    children: [
      {
        label: 'Name',
        prop: 'name',
        width: 120
      },
      {
        label: 'Address Info',
        children: [
          { label: 'State', prop: 'state', width: 120 },
          { label: 'City', prop: 'city', width: 120 },
          { label: 'Address', prop: 'address' },
          { label: 'Zip', prop: 'zip', width: 120 }
        ]
      }
    ]
  }
];
`

**Comment by fandog815** [comment]
这个组件不行，固定列都不可以，不能做到列表的固定不随着横向滚动。

**Comment by l-x-f** [comment]
release [v0.1.19]  https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md
