### ISSUE TITLE
PlusPage 能否新增setSearchFieldsValue方法，在外面控制PlusSearch的值

### ISSUE THREAD

**Issue by fiture** [plus-pro-components/plus-pro-components#222]
### 需要增强的组件/模块

PlusPage

## 目前：
1、PlusPage目前只能通过search.defaultValues参数搜索表单的默认值
2、且设置后点击“重置”按钮也会被重置为设定的默认值，无法真正清空

## 建议：
固提议希望暴露一个方法（setSearchFieldsValue）设置PlusSearch 的v-model，能够在外面直接控制PlusPage 里面的 PlusSearch 表单的各字段值。

**Comment by l-x-f** [comment]
已列为计划，下个版本就会增加此功能。

**Comment by l-x-f** [comment]
release [v0.1.17](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)

**Comment by fiture** [comment]
感谢🙏
