### ISSUE TITLE
PlusForm 的 footerAlign 无效，因为 footer 未设置 flex 布局，只有 justify-content，所以无效。

### ISSUE THREAD

**Issue by wangcai01** [plus-pro-components/plus-pro-components#224]
### plus-pro-components 版本

0.1.17

### vue 版本

3.5.12

### element-plus 版本

2.8.5

### 最小复现环境的链接

无

### 复现步骤

在 PlusForm 中添加 footerAlign="center"

### 期望的行为

居中对齐

### 实际的行为

默认左对齐

### 构建工具

Vite

**Comment by wangcai01** [comment]
![image](https://github.com/user-attachments/assets/f454b38b-2a7d-4143-9620-d53817ad70ba)

**Comment by l-x-f** [comment]
样式导入了吗？

**Comment by wangcai01** [comment]
哦哦，不好意思，没注意，样式忘导入了

> 样式导入了吗？
