### ISSUE TITLE
PlusDescriptions设置border为false不对element-plus生效

### ISSUE THREAD

**Issue by windlesszz** [plus-pro-components/plus-pro-components#226]
0.1.17PlusDescriptions设置border为false不对element-plus生效

**Comment by l-x-f** [comment]
已支持，仅在editable为false时生效，下个版本就会更新。

**Comment by l-x-f** [comment]
release [v0.1.18](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
