### ISSUE TITLE
抽屉表单submitLoading设置为true不生效

### ISSUE THREAD

**Issue by Lin-Van** [plus-pro-components/plus-pro-components#227]
### plus-pro-components 版本

0.1.17

### vue 版本

3.5.12

### element-plus 版本

2.8.5

### 最小复现环境的链接

https://playground.plus-pro-components.com/#eNqtWHtvG8cR/yoHogBpQCQl2W0BVRLcugqQwm2E2Gj/CAPkdLckz767vd7t6VGCgNwidZU4VgDDkZMocd1IcurEeiRG7CiJ/GV0R+pb5Ld7D96RSz0i8x+SO7O/eezM7M60Cr93nMq8TwoThUlGLMdUGZmu2YoySczynM8YtZXLmmloN6dqhaZq6yZ5wyF2rTAdrtwLflwO3/sp2FvpPvoy+OD+ZDXdE0HMmr73R1ddIO5r1LWU+bJFdWJOzBueMWcSAMa/aoWExtdU0ycelibq2ISFlqJR07dsb0RxfZN4SrtW4PDQi9p1Q/BEml2J/vO9nj9nGewqVXXDboDB8K6JlVqhCt0mqxlb8dfTXMNhiqkKXsale4T5DqiG5VCXKS3FJXWlrdRdailFOKyYktiSQ0Dnxl4Rio4orxnE1P8qDEn3OKCXHZeWNYp9NrGZB4yaDSM8Fls2pbS4ZbZqkQnlLWFktMI/Lvm7b7hEn1CY65ORZNkinqc2wF/s7jzvHtwL3t0MPvyg83gX6Jze5l9vC3amNs4DG/73dufpQQ62ZuM7sSE+pomMK956GzYJibE8U51DBCjFWMVY3IKhs+aEMjY+Gi/ATw64uCMSHhEX1+FrrGvUWUrWGaUmMzh3hBmuLwcbn4QPDjob+785fPEkeLrW+XpLaN0WW/o06bz3Xbh86yRNPKYy35Pp4hGTaCyhUIcZcEbq5oyjeyLD9Sfdx18E//422ZVigjiaXYRLqYtFnE/s98SKIdDB82+GQ4/JoOdAOx12BHz44qkMe1yGvURMky6cUvONve6zTRn0xRM9Ev1ANA454/DBTvDhVhQT/Sc92n/SCwbTmtKTjiiJFJmcte+O1p4le2NAZsiDWEf5KTuorMQdHp3h/d2j26t9iLZvzWGTBNOwHZ+V8/Q6L0az2ImobAGCaKi61J5QxkcUjxEAjkcelCoQPLwbvPhnnwKawdL8y+Wl6mmq3hN9bDZIAz4Re/Tx/e7my9zBNw1Tdwn0TsH6AHOg5RxsLow3XwbbK/3UIfASEX1iBgXlzu+jXe7BO/tpsCafXjKcUk4uewf89dUDLupVyMllcr+czq3Pw0ebUjn5BZGMElq6Li0G0kqVhuLe3rliYmx4TAQbT4K7D19NTEDM8TER7K4G+2vnPisu59iYCFY3Dvc3ePaeW86xMXH44nb4cDX8XG7SWcPipFoerIswzxckvOW0tMj2XgR4unS+Oeg82g7+s3u09mVn5U6w+lxaFxPxAqhJTRSxofszDyCpht2tW+Fef8nUiYU3qrRoNol2c44unukJEXz6afDu087+Y/kT4nT3+fajzvZauL5/uH8HSN2dW4ffb8nfDafCCz/ePlr+pLvz2XCk8TPc2f/bCv+VPmNiLzaMevrUyvrQxTufnsmB3Z2187ju5Xr40ffn8FXn4O7RF7mC8wtchKgM1x9KHx3E1q+f4t1xXCrwviZm508YF81Riqfg5aC6bLY/W46WV8L3/4++MHj8fl4vRYFKQ/g7P9wLP0vsODG7dp6FD+4OZJenyWxlZBF6EvVYQy110SR2I3oN9gxs0oW/UVe/aqBt7GuOVJ9Rz/gHJLQUy7DfpAvAw3MKSNHvS8nhRXbUbBxi0ibFTS8aI7SUpbpqeuRCSot6RkGazHSR06VWO2VKetkcwu8Saq9JB710QZmajiyNxVaECJC4Qbn2LddDK1OZrZxOsdWkjVKtELXWaKtrBaikpOpEyBEwtIEHCeMxSH1WKl2Ymo79LQOLkQaxhG0CrD2i/Hp0dJTbCZ0nq1HLjga9MFKIGvGypTqVGx61McsQstD1CwLa+fS0awW0axaa7zLvxzkBwwPGEA/Vqm87NxsVtOeYY/R4Lo9XLlYuVXXDY1XD1slipe6bZsW6gd1xQNQKkuZ+GLaENcbNQ17OKlE1uNvKmDsMgx3CntU7B29SXfWaZT5pkQOmDJcvVcZ+Wxkfi1cETBzVbTifeWIM0+hzPbfOMIn7RlSMc0eg8q7wT2Itk1bYw29CyfoNbzHSctYlHnHn4YSUhvRuEAQQJ89c+wvyPUPETAlzlWOJbxJEo891jNj+4PMscDN8QtvXRSQh6K97M4uM2LyDShXt1SqMr3yk0HDTe+perFzMeBGVcanhUgj/s2rYyUQunkv1zaIwsotnSpVqPL7rTaNaETcfwaDOcVWiGEvnUBVZBOLwACHfWUJuZvINf/KDQq7OwFANJsnFwKxUU3jiiu/igc1eRwFSbY3IJ2yDxhw3Uos3zUT5wPfG7NkMyYze5onLTxMlsShSPUPScHUwctWwb/JaiuCj5jzBGJLcwMhnRGmi/OarJGaIEbNONZ8Lq0QQsTKlIicXRbHjvyouMblcjy1h/NckhInrT5A4OGj8K11TdX1mHjhXkdTEJi7wMOEsco2Eaj3gQU7iuhQXfqy84EyVnKP6UkV1cGfoJb4dVHExmAS3DT8a0yQ6lBHluGarCypuHy76GlecB0hvaWY2XazZZFGcRd23NZ4LQ2ITV43woFFXSqm4C9CU+a4Ys8T3XhIkU5LI4fKAEP/jxuAm49c//1nxPVIaEHvijkwI9XhjV2Suz34jM46J7IoMUWyyoEABywB0fzD1wgjWplE3GHLFs1womudFscbfDkNVTQ/slSv7zgk3669ace61s9cUtH4nq3Wh/TOJihbf

### 复现步骤

设置属性:submitLoading="true" 点击确认按钮，并不会显示加载，另外确认只能自己加防抖函数防止重复点击吗

### 期望的行为

点击确认按钮，按钮可以显示加载

### 实际的行为

点击确认按钮，按钮没有显示加载

### 构建工具

Vite

**Comment by l-x-f** [comment]
使用 confirmLoading，文档疏漏未做说明。

**Comment by Lin-Van** [comment]
> 使用 confirmLoading，文档疏漏未做说明。

好的，谢谢
