### ISSUE TITLE
PlusLayout功能优化

### ISSUE THREAD

**Issue by mcode999** [plus-pro-components/plus-pro-components#236]
### 需要增强的组件/模块

PlusLayout

### 描述

使用PlusLayout的layout-extra，default，breadcrumb-item-title等插槽应该做样式隔离，纵向滚动条应该只出现在default插槽中，目前采用定位属性实现，但是组件带的滚动条显示在el-main内而不是default插槽内
![image](https://github.com/user-attachments/assets/a425a8c1-a10d-4df7-9606-6135198916f3)
（ps:组件有计划提供动态布局吗）

**Comment by l-x-f** [comment]
release [v0.1.19]  https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md
