### ISSUE TITLE
vite打包报错

### ISSUE THREAD

**Issue by liferyy** [plus-pro-components/plus-pro-components#238]
### plus-pro-components 版本

0.1.18

### vue 版本

3.5.13

### element-plus 版本

2.9.0

### 最小复现环境的链接

https://github.com/plus-pro-components/plus-pro-components/blob/dev/packages/components/search/style/css.ts

### 复现步骤

![image](https://github.com/user-attachments/assets/f88f8957-b26f-4e6b-ad95-3e4ab0aca4cf)
组件中加上这两行css
npm run build

### 期望的行为

打包成功

### 实际的行为

![image](https://github.com/user-attachments/assets/d42a87b6-0f78-4d51-8974-3b5d64f9bdce)

### 系统信息

```shell
vite v3.2.11
"node": "16.15.0",
"npm": "8.5.5"
```

### 构建工具

Vite

**Comment by l-x-f** [comment]
建议 更新vite 到4.2.0以上。
