### ISSUE TITLE
不支持element-plus命名空间

### ISSUE THREAD

**Issue by xusaihu** [plus-pro-components/plus-pro-components#47]
https://element-plus.gitee.io/zh-CN/guide/namespace.html

**Comment by l-x-f** [comment]
计划在v0.0.1-beta.18 版本支持。

**Comment by l-x-f** [comment]
v0.0.1-beta.18 版本已经发布，命名空间和暗黑模式都得到支持。
文档链接 [https://plus-pro-components.com/guide/namespace.html](https://plus-pro-components.com/guide/namespace.html)
