### ISSUE TITLE
希望可以提供类似ProComponents的"多选卡片"组件

### ISSUE THREAD

**Issue by aliothor** [plus-pro-components/plus-pro-components#50]
[CheckCard组件参考](https://procomponents.ant.design/components/check-card)
![image](https://github.com/plus-pro-components/plus-pro-components/assets/60435548/1f1a7fcb-b2f2-446f-9b48-f0e81295eea9)

**Comment by l-x-f** [comment]
> [CheckCard组件参考](https://procomponents.ant.design/components/check-card) ![image](https://user-images.githubusercontent.com/60435548/284918399-1f1a7fcb-b2f2-446f-9b48-f0e81295eea9.png)

安排，下个版本。

**Comment by l-x-f** [comment]
安排，下个版本。

**Comment by l-x-f** [comment]
0.0.1-beta.26  
 [CheckCard ](https://plus-pro-components.com/components/check-card.html) 
 [CheckCardGroup  ](https://plus-pro-components.com/components/check-card-group.html)

**Comment by l-x-f** [comment]
0.0.1-beta.26
