### ISSUE TITLE
Vite 手动配置optimizeDeps.include预加载异常

### ISSUE THREAD

**Issue by fgy888** [plus-pro-components/plus-pro-components#52]
异常截图：
![image](https://github.com/plus-pro-components/plus-pro-components/assets/150577286/6d282ce2-3684-44e7-9602-707059742c44)

optimizeDeps.include plus-pro-components配置核心程序：（steps-form，descriptions组件异常已经跳过）
![image](https://github.com/plus-pro-components/plus-pro-components/assets/150577286/23e93334-03a5-418b-bf21-23a0b872193e)

导致原因：
以下两个文件截图圈出的文件名与theme-chalk/src/目录下不一致
1、components/steps-form/style/index
![image](https://github.com/plus-pro-components/plus-pro-components/assets/150577286/5698290a-5a29-44b2-88d3-d12d11eac130)

2、components/descriptions/style/index
![image](https://github.com/plus-pro-components/plus-pro-components/assets/150577286/04daa7af-f39b-492c-86d3-76a89de7e570)

**Comment by l-x-f** [comment]
This issue has been resolved  [ v0.0.1-beta.26 ](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)

**Comment by fgy888** [comment]
@l-x-f 还有漏网之鱼sidebar😂
![image](https://github.com/plus-pro-components/plus-pro-components/assets/150577286/d634a827-e2c6-404b-87d7-fecd3257d1e1)

**Comment by l-x-f** [comment]
ok，下个版本修复。
