### ISSUE TITLE
Page组件设置search属性modelValue异常

### ISSUE THREAD

**Issue by fgy888** [plus-pro-components/plus-pro-components#53]
项目代码
![image](https://github.com/plus-pro-components/plus-pro-components/assets/150577286/397473d3-78cf-4754-80f5-5c9f8431f817)

导致原因：应该是plus-pro-components page组件源码v-model和用户传递的modelValue存在冲突
![image](https://github.com/plus-pro-components/plus-pro-components/assets/150577286/fe37326d-f7df-4463-9493-dac6cbbbefe6)

麻烦作者给个page组件设置search组件默认查询条件示例🙂

**Comment by l-x-f** [comment]
下个版本添加默认支持。

**Comment by fgy888** [comment]
> 下个版本添加默认支持。

可以快些发布吗😁

**Comment by l-x-f** [comment]
今天18:00点之前会发布一个新版本。

**Comment by fgy888** [comment]
> page组件设置search组件默认查询条件示例

建议官网page组件给个设置search组件默认查询条件示例

**Comment by l-x-f** [comment]
ok

**Comment by l-x-f** [comment]
[v0.0.1-beta.27](https://plus-pro-components.com/)
[page 默认搜索参数](https://plus-pro-components.com/components/page.html#%E9%BB%98%E8%AE%A4%E6%90%9C%E7%B4%A2%E5%8F%82%E6%95%B0)

**Comment by l-x-f** [comment]
[v0.0.1-beta.27](https://plus-pro-components.com/)
[page 默认搜索参数](https://plus-pro-components.com/components/page.html#%E9%BB%98%E8%AE%A4%E6%90%9C%E7%B4%A2%E5%8F%82%E6%95%B0)

**Comment by fgy888** [comment]
> [v0.0.1-beta.27](https://plus-pro-components.com/) [page 默认搜索参数](https://plus-pro-components.com/components/page.html#%E9%BB%98%E8%AE%A4%E6%90%9C%E7%B4%A2%E5%8F%82%E6%95%B0)

valueType: 'date-picker'类型组件通过search.defaultValues设置默认值还是异常（其他类型好像是ok的），麻烦作者验证下。
目前临时通过renderField自定义组件可以解决：
![image](https://github.com/plus-pro-components/plus-pro-components/assets/150577286/8e17898c-6bf9-43cb-8669-610c973fdd00)

**Comment by l-x-f** [comment]
ok
