### ISSUE TITLE
Search组件不支持控制重置、搜索按钮顺序

### ISSUE THREAD

**Issue by fgy888** [plus-pro-components/plus-pro-components#54]
![image](https://github.com/plus-pro-components/plus-pro-components/assets/150577286/91bc5b84-19e4-4070-babb-b6469781964e)

**Comment by l-x-f** [comment]
解决方式：
1. 现在版本可以修改css，改变顺序。  [示例](https://codepen.io/l-x-f/pen/KKJremq)
2. 下个版本增加slots自定义。
