### ISSUE TITLE
getList方法query中传的pageSize默认是10可以进行自定义吗，比如我想默认传的是20。

### ISSUE THREAD

**Issue by fsyplus** [plus-pro-components/plus-pro-components#55]
getList方法query中传的pageSize默认是10可以进行自定义吗，比如我想默认传的是20。

**Comment by l-x-f** [comment]
下个版本中提供支持。

**Comment by l-x-f** [comment]
[v0.0.1-beta.28](https://plus-pro-components.com/)
[page 默认分页参数](https://plus-pro-components.com/components/page.html#%E9%BB%98%E8%AE%A4%E5%88%86%E9%A1%B5%E5%8F%82%E6%95%B0)
