### ISSUE TITLE
table actionsBar 的 confirm 操作按钮国际化无效

### ISSUE THREAD

**Issue by KeJunMao** [plus-pro-components/plus-pro-components#62]
推荐的解决方法：

[应用程序上下文继承](https://element-plus.org/zh-CN/component/message-box.html#%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E4%B8%8A%E4%B8%8B%E6%96%87%E7%BB%A7%E6%89%BF-2-0-4
)
```ts
import { getCurrentInstance } from 'vue'
import { ElMessageBox } from 'element-plus'

// 在你的 setup 方法中
const { appContext } = getCurrentInstance()!
// 你可以像这样传递参数：
ElMessageBox({}, appContext)
// 或者正在使用不同的调用方式
ElMessageBox.alert('Hello world!', 'Title', {}, appContext)
```

linked: 
- https://github.com/element-plus/element-plus/issues/6494

**Comment by l-x-f** [comment]
需要提供最小bug复现代码，需要注明 vue版本， element-plus版本，plus-pro-components版本。

**Comment by KeJunMao** [comment]
你好，这个用您项目的 playground 就能复现

只要在 #L214 加上 appContext 就行
```diff
- ElMessageBox.confirm(message, title, options) 
+ ElMessageBox.confirm(message, title, options, appContext ) 
```
https://github.com/plus-pro-components/plus-pro-components/blob/452e248d73669a0e1fe2ea61b4356ce024464168/packages/components/table/src/table-action-bar.vue#L214-L220

**Comment by KeJunMao** [comment]
当然，目前我是通过手动传递 `cancel-button-text` 和 `confirm-button-text`：

```ts
...
confirmButtonText: t('el.popconfirm.confirmButtonText')
...
```

这算是 element-plus 的 bug，如果不愿意加 appContext 的话，给一个传递 context 的口也行~

**Comment by l-x-f** [comment]
👍

**Comment by KeJunMao** [comment]
> 需要提供最小bug复现代码，需要注明 vue版本， element-plus版本，plus-pro-components版本。

- Operating System: Windows_NT
- Node Version:     v18.19.0
- Package Manager:  pnpm@8.1.1
- Dependencies:
	
	"element-plus": "^2.4.4",
    "plus-pro-components": "0.0.1-beta.31",
    "vue": "^3.3.11"

```vue
<script setup>
import { computed, ref } from "vue";

// components
import { ElConfigProvider, ElButton } from "element-plus";
import { PlusTable } from "plus-pro-components";

// css
import "plus-pro-components/es/components/table/style/css";
import "element-plus/theme-chalk/index.css";

// i18n
import ZhCN from "element-plus/es/locale/lang/zh-cn";
import En from "element-plus/es/locale/lang/en";
import extraZhCn from "plus-pro-components/es/locale/lang/zh-cn";
import extraEn from "plus-pro-components/es/locale/lang/en";

const lang = ref("en");
const locale = computed(() =>
  lang.value === "en" ? { ...En, ...extraEn } : { ...ZhCN, ...extraZhCn }
);

const data = [{}];
const tableConfig = [];
const actionsBar = ref({
  buttons: [{ text: "Delete", confirm: {} }],
});
</script>

<template>
  <ElConfigProvider :locale="locale">
    <ElButton @click="lang = lang === 'en' ? 'zh-cn' : 'en'">
      {{ locale.name }}
    </ElButton>
    <PlusTable
      :action-bar="actionsBar"
      :columns="tableConfig"
      :table-data="data"
    />
  </ElConfigProvider>
</template>
```

**Comment by l-x-f** [comment]
v0.0.1-beta.32 [ ActionBarButtonsRow.confirm](https://plus-pro-components.com/components/type.html#actionbarbuttonsrow)
