### ISSUE TITLE
Question: 为何不为 `dialog-form` 提供 `plus-field-*` 插槽？

### ISSUE THREAD

**Issue by KeJunMao** [plus-pro-components/plus-pro-components#63]
俺的建议是同样提供动态插槽，用 `renderField` 不是特别方便

或者提供 `plus-form` 插槽，允许完全自定义 `PlusForm`, 这个您实现起来也比较简单

**Comment by l-x-f** [comment]
建议很好，后续版本考虑增加。

**Comment by l-x-f** [comment]
v0.0.1-beta.32 [dialog-form.自定义表单项](https://plus-pro-components.com/components/dialog-form.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%8D%95%E9%A1%B9)
