### ISSUE TITLE
Pref: 默认情况下， PlusDialogForm 的 form-footer 插槽无意义

### ISSUE THREAD

**Issue by KeJunMao** [plus-pro-components/plus-pro-components#67]
因为 `has-footer` 默认始终为 `false`

https://github.com/plus-pro-components/plus-pro-components/blob/2676231c1be00393cca35d6a28293499416f2dc1/packages/components/dialog-form/src/index.vue#L20-L25

我在使用时很困惑为什么不显示，直到我查看了源码。

如果将其改为 `$slots['form-footer']` 存在时 `has-footer` 为 true 是否更合理？

> 感谢您的超及时回复，以及对我疯狂开 issues 的迅速处理 ♥

**Comment by l-x-f** [comment]
fixed [v0.0.1-beta.34](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
