### ISSUE TITLE
Feature Request: 允许自定义含 `options` 的 `display-item` 的 `getStatus` 逻辑

### ISSUE THREAD

**Issue by KeJunMao** [plus-pro-components/plus-pro-components#68]
现在是固定的按 `.value` 来判断的，要和别的一起判断的话不是很方便

https://github.com/plus-pro-components/plus-pro-components/blob/af58bf4191be96a66973df151486eb8269a70d1f/packages/components/display-item/src/index.vue#L241C1-L247C3

**Comment by l-x-f** [comment]
等后续版本计划。

**Comment by l-x-f** [comment]
[0.0.1-beta.36](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
