### ISSUE TITLE
add form 动态隐藏以及动态禁用就完美了

### ISSUE THREAD

**Issue by zoujinglong666** [plus-pro-components/plus-pro-components#70]
add form 动态隐藏以及动态禁用就完美了

**Comment by l-x-f** [comment]
应该支持的呀 @zoujinglong666

**Comment by zoujinglong666** [comment]
![image](https://github.com/plus-pro-components/plus-pro-components/assets/83895241/af614fd6-b107-42c9-9193-f0c22f69bf06) 看到了 我用用

**Comment by l-x-f** [comment]
使用有任何问题，欢迎issues

**Comment by zoujinglong666** [comment]
我使用了是不能的，你们可以看一下vben的设计

**Comment by l-x-f** [comment]
复现代码提供一下。

**Comment by zoujinglong666** [comment]
能简单隐藏但是不能动态隐藏  好比举个例子 我一个表单里
![image](https://github.com/plus-pro-components/plus-pro-components/assets/83895241/018968f7-0f48-4028-a0be-ae804abb0f43)wo'xain我现在设置状态为未解决的值时候 第一个输入框应该禁用

**Comment by zoujinglong666** [comment]
> 复现代码提供一下。

这并不是功能bug

**Comment by zoujinglong666** [comment]
只是说你们暂时没考虑到这一步  但是已经很好用了

**Comment by l-x-f** [comment]
你看这个是你想要的吗?
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/element-plus/dist/index.css" />
    <!-- 导入vue3 -->
    <script src="https://cdn.jsdelivr.net/npm/vue@3"></script>
    <!-- 导入element-plus -->
    <script src="https://cdn.jsdelivr.net/npm/element-plus"></script>

    <!-- 导入plus-pro-components样式 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/plus-pro-components/index.css" />
    <!--导入plus-pro-components"  -->
    <script src="https://cdn.jsdelivr.net/npm/plus-pro-components"></script>
  </head>
  <body>
    <div id="app">
      <el-card>
        <plus-form v-model="state" :columns="columns" />
      </el-card>
    </div>

    <script>
      const { createApp, ref, reactive, watch, computed } = Vue
      const App = {
        setup() {
          const state = reactive({
            status: '1',
            name: ''
          })

          const columns = ref([
            {
              label: '名称',
              width: 120,
              prop: 'name',
              valueType: 'copy',
              tooltip: '名称最多显示6个字符'
            },
            {
              label: '名称1',
              width: 120,
              prop: 'name',
              valueType: 'copy',
              tooltip: '名称最多显示6个字符',
              hideInForm: computed(() => state.status === '0')
            },
            {
              label: '状态',
              width: 120,
              prop: 'status',
              valueType: 'select',
              options: [
                {
                  label: '未解决',
                  value: '0',
                  color: 'red'
                },
                {
                  label: '已解决',
                  value: '1',
                  color: 'blue'
                }
              ]
            }
          ])

          watch(state, val => {
            if (val.status === '0') {
              columns.value[0].fieldProps = {
                disabled: true
              }
            } else {
              columns.value[0].fieldProps = {
                disabled: false
              }
            }
            console.log(columns.value)
          })

          return {
            state,
            columns
          }
        }
      }
      const app = createApp(App)
      app.use(ElementPlus)
      app.use(PlusProComponents)
      app.mount('#app')
    </script>
  </body>
</html>

```

**Comment by zoujinglong666** [comment]
![image](https://github.com/plus-pro-components/plus-pro-components/assets/83895241/2666fb8a-881d-4977-a501-714916eb91c8)
这里做成  hideInForm: computed(() => state.status === '0') 这种形式会优雅更多  意思是那个意思

**Comment by zoujinglong666** [comment]
> 你看这个是你想要的吗?
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="UTF-8" />
>     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>     <title>Document</title>
>     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/element-plus/dist/index.css" />
>     
>     <script src="https://cdn.jsdelivr.net/npm/vue@3"></script>
>     
>     <script src="https://cdn.jsdelivr.net/npm/element-plus"></script>
> 
>     
>     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/plus-pro-components/index.css" />
>     
>     <script src="https://cdn.jsdelivr.net/npm/plus-pro-components"></script>
>   </head>
>   <body>
>     <div id="app">
>       <el-card>
>         <plus-form v-model="state" :columns="columns" />
>       </el-card>
>     </div>
> 
>     <script>
>       const { createApp, ref, reactive, watch, computed } = Vue
>       const App = {
>         setup() {
>           const state = reactive({
>             status: '1',
>             name: ''
>           })
> 
>           const columns = ref([
>             {
>               label: '名称',
>               width: 120,
>               prop: 'name',
>               valueType: 'copy',
>               tooltip: '名称最多显示6个字符'
>             },
>             {
>               label: '名称1',
>               width: 120,
>               prop: 'name',
>               valueType: 'copy',
>               tooltip: '名称最多显示6个字符',
>               hideInForm: computed(() => state.status === '0')
>             },
>             {
>               label: '状态',
>               width: 120,
>               prop: 'status',
>               valueType: 'select',
>               options: [
>                 {
>                   label: '未解决',
>                   value: '0',
>                   color: 'red'
>                 },
>                 {
>                   label: '已解决',
>                   value: '1',
>                   color: 'blue'
>                 }
>               ]
>             }
>           ])
> 
>           watch(state, val => {
>             if (val.status === '0') {
>               columns.value[0].fieldProps = {
>                 disabled: true
>               }
>             } else {
>               columns.value[0].fieldProps = {
>                 disabled: false
>               }
>             }
>             console.log(columns.value)
>           })
> 
>           return {
>             state,
>             columns
>           }
>         }
>       }
>       const app = createApp(App)
>       app.use(ElementPlus)
>       app.use(PlusProComponents)
>       app.mount('#app')
>     </script>
>   </body>
> </html>
> ```

差不多就是这种效果

**Comment by zoujinglong666** [comment]
![image](https://github.com/plus-pro-components/plus-pro-components/assets/83895241/d8c95a81-8c80-4666-963d-bcadd21d20c9)
zhe'jiu这样就可以了

**Comment by zoujinglong666** [comment]
这个组件好好维护下去大有可为

**Comment by l-x-f** [comment]
后续版本 fieldProps考虑增加 ref 和computed支持。

**Comment by zoujinglong666** [comment]
> 后续版本 fieldProps考虑增加 ref 和computed支持。

现在用ref可以  反而reactive有问题

**Comment by l-x-f** [comment]
ok

**Comment by l-x-f** [comment]
已支持  [0.0.1-beta.37](https://plus-pro-components.com/components/form.html#%E6%95%B0%E6%8D%AE%E5%B1%9E%E6%80%A7%E8%81%94%E5%8A%A8)
