### ISSUE TITLE
options直接赋值无效

### ISSUE THREAD

**Issue by zoujinglong666** [plus-pro-components/plus-pro-components#72]
![image](https://github.com/plus-pro-components/plus-pro-components/assets/83895241/a5df2bd7-1f83-474d-a8cb-abc373ca436f)

**Comment by l-x-f** [comment]
options支持数组，computed，函数，和 Promise。[columns ](https://plus-pro-components.com/components/config.html)。
建议改成 computed或者 函数返回一个Promise

**Comment by zoujinglong666** [comment]
直接赋值不行吗

**Comment by zoujinglong666** [comment]
![image](https://github.com/plus-pro-components/plus-pro-components/assets/83895241/d129aa1e-f2a8-41a0-81a7-42216a1e4228)
这样还是不行

**Comment by l-x-f** [comment]
建议看下 [PlusForm 异步（动态）数据用法](https://plus-pro-components.com/components/form.html#%E5%BC%82%E6%AD%A5-%E5%8A%A8%E6%80%81-%E6%95%B0%E6%8D%AE%E7%94%A8%E6%B3%95) 文档

**Comment by l-x-f** [comment]
[PlusProComponents  options demos](https://codepen.io/l-x-f/pen/MWxVRea)

**Comment by zoujinglong666** [comment]
不知道是不是我没更新

**Comment by zoujinglong666** [comment]
可能是我单独移植出来使用导致的失效
