### ISSUE TITLE
PlusForm daterange 中赋初始值会报错

### ISSUE THREAD

**Issue by liu-jia-yi** [plus-pro-components/plus-pro-components#74]
![image](https://github.com/plus-pro-components/plus-pro-components/assets/20166121/1c5fd630-d49f-4c09-aa6d-7d7353a6daca)

![image](https://github.com/plus-pro-components/plus-pro-components/assets/20166121/7e09b448-7206-41fe-b9fa-9b23eb381b27)

**Comment by l-x-f** [comment]
提供一下  [环境 ](https://plus-pro-components.com/guide/contribution.html)

**Comment by liu-jia-yi** [comment]
浏览器 122.0.6261.129（正式版本） （64 位）
操作系统 Windows 11 家庭中文版 23H2
node v20.11.1
vite 5.1.5
vue 3.4.21
element-plus 2.6.0
plus-pro-components 0.0.3

**Comment by liu-jia-yi** [comment]
补充一下，使用 slot 没有问题。
![image](https://github.com/plus-pro-components/plus-pro-components/assets/20166121/d42223b2-27d9-4a53-a7ce-def253f45320)

**Comment by l-x-f** [comment]
fixed by [v0.0.4](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md).
