### ISSUE TITLE
表单配置宽度无效反馈

### ISSUE THREAD

**Issue by newives** [plus-pro-components/plus-pro-components#77]
<img width="786" alt="图片" src="https://github.com/plus-pro-components/plus-pro-components/assets/81661030/b8e2f7d3-5753-4b4d-99a8-cf8771c48159">
<img width="996" alt="图片" src="https://github.com/plus-pro-components/plus-pro-components/assets/81661030/7db7ec8f-2c4d-454a-8d46-d77c45abc2ef">

**Comment by l-x-f** [comment]
width  仅适用于表格  [参考配置](https://plus-pro-components.com/components/config.html)
要调整表单宽度 使用colProps [参考表单示例-混合]( https://plus-pro-components.com/components/form.html#%E6%B7%B7%E5%90%88)

**Comment by newives** [comment]
那等于是不能固定宽度吗

**Comment by l-x-f** [comment]
要定宽 可以给表单外层容器固定宽，可以配合
```js
{
   formItemProps: {
      style: {
        width: '100px' // 示例
      }
    }
}
```
使用。

**Comment by newives** [comment]
可以了 感谢 不够会有ts报错

<img width="902" alt="图片" src="https://github.com/plus-pro-components/plus-pro-components/assets/81661030/72ab22a9-4c1b-40fb-834f-70dac9289f0c">

**Comment by l-x-f** [comment]
可以先用断言
```ts
{
   formItemProps: {
      style: {
        width: '100px' // 示例
      }
    } as any
}
```
或者注释
```ts
{
  formItemProps: {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      style: {
        width: '100px'
      }
    }
}
```
解决，后续版本会升级ts类型。
