### ISSUE TITLE
搜索组件的footer区是否可以一直靠右显示呢

### ISSUE THREAD

**Issue by newives** [plus-pro-components/plus-pro-components#78]
例如 antd 的 pro-components

https://pro-components.antdigital.dev/playground#crud

https://preview.pro.ant.design/list/table-list

**Comment by newives** [comment]
<img width="1098" alt="图片" src="https://github.com/plus-pro-components/plus-pro-components/assets/81661030/608bc8b1-a77d-4d99-b5c7-bcf5b280b9ec">

<img width="1247" alt="图片" src="https://github.com/plus-pro-components/plus-pro-components/assets/81661030/f7d6c5a5-c5c3-43bf-95f3-155d06526dbb">

**Comment by l-x-f** [comment]
建议非常好，是想要这样的效果吗？

![image](https://github.com/plus-pro-components/plus-pro-components/assets/33000154/30a25974-0801-498f-b377-825744d6818a)

**Comment by newives** [comment]
是的哈 帅哥

**Comment by xiaoxian521** [comment]
哈哈 期待中 很优秀的轮子 👍

<img width="1253" alt="image" src="https://github.com/plus-pro-components/plus-pro-components/assets/44761321/f5aca635-68bb-477a-a564-e8df3071e180">

**Comment by l-x-f** [comment]
@xiaoxian521  感谢大佬认可🤝。

**Comment by xiaoxian521** [comment]
哈哈 还是要感谢你呀 这么好的轮子 加油❤️

**Comment by l-x-f** [comment]
[v0.0.5](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)已支持。
