### ISSUE TITLE
element-plus v2.6.0版本的变化需要兼容

### ISSUE THREAD

**Issue by newives** [plus-pro-components/plus-pro-components#79]
具体来自 https://github.com/element-plus/element-plus/issues/15834#issuecomment-1936919759

目前如果用最新版element-plus和plus-pro-components搭配会报警告

<img width="669" alt="图片" src="https://github.com/plus-pro-components/plus-pro-components/assets/81661030/d5120f0b-5f58-4f22-b1f3-88be412ee786">

**Comment by l-x-f** [comment]
后续版本会做兼容。

**Comment by l-x-f** [comment]
[v0.0.5](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)已兼容element-plus@2.6.0
