### ISSUE TITLE
搜索组件的展开和折叠可以暴露个事件吗？

### ISSUE THREAD

**Issue by liu-jia-yi** [plus-pro-components/plus-pro-components#80]
### 需要增强的组件

PlusSearch

### 描述

希望展开和折叠时能暴露一个事件。

**Comment by l-x-f** [comment]
可以的

**Comment by l-x-f** [comment]
[v0.0.6](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md) 已添加
