### ISSUE TITLE
Search 中，columns 计算属性，数据未更新到页面

### ISSUE THREAD

**Issue by nineaiyu** [plus-pro-components/plus-pro-components#84]
### plus-pro-components 版本

0.0.6

### vue 版本

最新

### element-plus 版本

最新

### 最小复现环境的链接

无

### 复现步骤

定义一个columns 的计算属性
```
const choicesDict = ref([]);

const columns : PlusColumn[] = computed(() => {
    return [
      {
        label: t("permission.mode"),
        prop: "mode_type",
        valueType: "select",
        options: choicesDict.value
      }
    ];
  });
```

通过api接口将数据赋值给 choicesDict

然后页面上面拿不到这个选择器的数据
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/f6da7ae0-5d34-4b08-a773-2ff23acb19a9)

但是我将这个框放到后面，超出默认显示的搜索框数量，然后点击展开，则可以显示api的数据
![image](https://github.com/plus-pro-components/plus-pro-components/assets/19207867/3be2c104-8c2a-47e0-bc75-f805770ca9be)

### 期望的行为

正常渲染页面

### 实际的行为

展开后的数据可以正常渲染，默认显示的未渲染

### 构建工具

Vite

**Comment by l-x-f** [comment]
1. options 支持数组，computed，函数，和 Promise。参考[columns 配置](https://plus-pro-components.com/components/config.html)，[OptionsType](https://plus-pro-components.com/components/type.html#optionstype)。上文示例中给的是`choicesDict.value` 并不支持。
2. computed 在小于0.0.6 版本中存在引用失效，所有computed 暂时没法用，下个版本修复。
3.  现版本解决方案，建议使用函数,返回一个 Promise。
```js
// 示例
 options: async () => {  
      return [
        {
          label: 'pending',
          value: '0'
        },
        {
          label: 'fulfilled',
          value: '1'
        },
        {
          label: 'rejected',
          value: '1'
        }
      ]
    }
```

**Comment by nineaiyu** [comment]
hello, 什么时候发布新版？已经迫不及待了

**Comment by kobetwenty-four** [comment]
@nineaiyu 今天下午会发布一个版本

**Comment by l-x-f** [comment]
fixed [v0.0.7](https://github.com/plus-pro-components/plus-pro-components/blob/dev/CHANGELOG.md)
