### ISSUE TITLE
找不到模块“plus-pro-components/locale/zh-cn”或其相应的类型声明。

### ISSUE THREAD

**Issue by RJQingHuan** [plus-pro-components/plus-pro-components#87]
![image](https://github.com/plus-pro-components/plus-pro-components/assets/53939074/e6228e29-21de-41e6-b6d9-fff066835a9b)

请问这个怎么解决呢?

**Comment by kobetwenty-four** [comment]
用``` import plusZhCn from 'plus-pro-components/es/locale/lang/zh-cn' ```代替  或者   自定义module

**Comment by RJQingHuan** [comment]
谢谢
