### ISSUE TITLE
table form复用PlusColumn

### ISSUE THREAD

**Issue by RJQingHuan** [plus-pro-components/plus-pro-components#94]
### 需要增强的组件/模块

table form

### 描述

table form使用同一个PlusColumn,是否可以单独设置valueType的值,或者有其他实现方法吗?

**Comment by l-x-f** [comment]
1. 可以给2个配置，第一个只在表格中显示，第二个只在表单中显示。
```
const columns: PlusColumn[] = [
// 只在表格中显示
  {
    label: '名称',
    width: 120,
    prop: 'name',
    valueType: 'progress',
    hideInForm: true  
  },

// 只在表单中显示
 {
    label: '名称',
    width: 120,
    prop: 'name',
    valueType: 'select',
   hideInTable: true
  },
]
```
2. 可以使用 render/renderField函数，带‘render’ 的函数优先级最高，可实现任意自定义。
3. 可以使用插槽，也可实现任意自定义。

**Comment by RJQingHuan** [comment]
2,3都是valueType实现不了的情况才使用.

使用1也会有一些重复数据,是否可以考虑加两个字段,给form, table单独设置valueType?

**Comment by l-x-f** [comment]
嗯嗯，暂时不考虑单独 valueType。
